import { AppState, ReservationDraft, WaitlistEntry } from './types';
import { addMinutes, bookingCheck, canMarkNoShow, cancellationDecision, depositClosed, getReservation, getService, offerExpired, waitlistMatches } from './rules';
import { policyProblems } from './policy';
function next<T extends AppState>(state:T){const n=structuredClone(state);n.revision+=1;return n;}
function id(prefix:string){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;}
function audit(state:AppState,type:any,entityId:string,message:string,at=state.simulatedNow){state.audit.unshift({id:id('AUD'),at,type,entityId,message});state.audit=state.audit.slice(0,5000);}
export function createReservation(state:AppState,draft:ReservationDraft){
  const check=bookingCheck(state,draft);if(!check.ok)throw Error(check.reasons.join(' '));if(!state.customers.some(c=>c.id===draft.customerId))throw Error('고객을 찾을 수 없습니다.');
  const n=next(state);const svc=getService(n,draft.serviceId);const deposit=n.policy.requireDeposit?svc.deposit:0;const rid=id('RSV');n.reservations.unshift({id:rid,customerId:draft.customerId,serviceId:draft.serviceId,staffId:draft.staffId,startAt:draft.startAt,endAt:check.endAt,status:'requested',depositStatus:deposit?'unpaid':'not_required',depositAmount:deposit,createdAt:n.simulatedNow,source:draft.source??'manual',note:draft.note??''});audit(n,'reservation',rid,'예약 요청을 만들었습니다.');return n;
}
export function payDeposit(state:AppState,reservationId:string){const n=next(state);const r=getReservation(n,reservationId);if(depositClosed(r))throw Error('취소·완료·노쇼 처리된 예약에는 예약금을 결제할 수 없습니다.');if(r.depositStatus==='not_required')throw Error('예약금이 필요하지 않은 예약입니다.');if(r.depositStatus!=='unpaid')throw Error('현재 상태에서는 예약금을 다시 처리할 수 없습니다.');r.depositStatus='paid';audit(n,'deposit',r.id,`예약금 ${r.depositAmount.toLocaleString()}원을 모의 결제했습니다.`);return n;}
export function confirmReservation(state:AppState,reservationId:string){const n=next(state);const r=getReservation(n,reservationId);if(r.status!=='requested')throw Error('예약 요청 상태에서만 확정할 수 있습니다.');if(r.depositStatus==='unpaid')throw Error('예약금 모의 결제를 먼저 완료하세요.');const check=bookingCheck(n,{customerId:r.customerId,serviceId:r.serviceId,staffId:r.staffId,startAt:r.startAt},r.id);if(!check.ok)throw Error(check.reasons.join(' '));r.status='confirmed';audit(n,'reservation',r.id,'예약을 확정했습니다.');return n;}
export function cancelReservation(state:AppState,reservationId:string,reason:string){const n=next(state);const r=getReservation(n,reservationId);const decision=cancellationDecision(n,r);if(!decision.allowed)throw Error(decision.message);r.status='cancelled';r.cancelReason=reason||'사유 미입력';r.cancelledAt=n.simulatedNow;if(decision.depositOutcome==='refund')r.depositStatus='refunded';if(decision.depositOutcome==='forfeit')r.depositStatus='forfeited';audit(n,'cancel',r.id,`${decision.message} 예약금을 ${decision.depositOutcome==='refund'?'모의 환불':decision.depositOutcome==='forfeit'?'모의 차감':'변경하지 않음'} 처리했습니다.`);const matches=waitlistMatches(n,{reservationId:r.id,serviceId:r.serviceId,staffId:r.staffId,startAt:r.startAt,endAt:r.endAt});if(matches.length)audit(n,'waitlist',r.id,`취소 빈자리와 맞는 대기 고객 ${matches.length}명을 찾았습니다.`);return n;}
export function markArrived(state:AppState,reservationId:string){const n=next(state);const r=getReservation(n,reservationId);if(r.status!=='confirmed')throw Error('확정 예약만 도착 처리할 수 있습니다.');r.status='arrived';audit(n,'reservation',r.id,'고객 도착을 기록했습니다.');return n;}
export function completeReservation(state:AppState,reservationId:string){const n=next(state);const r=getReservation(n,reservationId);if(!['arrived','confirmed'].includes(r.status))throw Error('도착 또는 확정 상태에서만 완료 처리할 수 있습니다.');r.status='completed';const c=n.customers.find(c=>c.id===r.customerId);if(c)c.visitCount+=1;audit(n,'reservation',r.id,'서비스를 완료 처리했습니다.');return n;}
export function markNoShow(state:AppState,reservationId:string){const n=next(state);const r=getReservation(n,reservationId);if(r.status!=='confirmed')throw Error('확정된 예약만 노쇼 처리할 수 있습니다.');if(!canMarkNoShow(n,r))throw Error(`예약 시작 후 ${n.policy.noShowGraceMin}분이 지나야 노쇼 처리할 수 있습니다.`);r.status='no_show';let settled=r.depositStatus==='not_required'?'예약금이 필요 없는 예약이라 예약금은 처리하지 않았습니다.':'결제된 예약금이 없어 예약금은 처리하지 않았습니다.';if(r.depositStatus==='paid'){if(n.policy.noShowForfeit){r.depositStatus='forfeited';settled='예약금을 모의 차감했습니다.';}else{r.depositStatus='refunded';settled='예약금을 모의 환불했습니다.';}}const c=n.customers.find(c=>c.id===r.customerId);if(c)c.noShowCount+=1;audit(n,'noshow',r.id,`노쇼를 기록했습니다. ${settled}`);return n;}
export function addWaitlist(state:AppState,input:Omit<WaitlistEntry,'id'|'status'|'createdAt'>){const n=next(state);if(!n.customers.some(c=>c.id===input.customerId))throw Error('고객을 찾을 수 없습니다.');if(new Date(input.windowStart)>=new Date(input.windowEnd))throw Error('희망 시간 범위를 확인하세요.');const wid=id('WAIT');n.waitlist.unshift({...input,id:wid,status:'waiting',createdAt:n.simulatedNow});audit(n,'waitlist',wid,'대기 명단에 등록했습니다.');return n;}
export function offerCancelledSlot(state:AppState,waitId:string,cancelledReservationId:string){const n=expireOffers(state);n.revision+=1;const w=n.waitlist.find(x=>x.id===waitId);if(!w||w.status!=='waiting')throw Error('대기 중인 항목만 제안할 수 있습니다.');const r=getReservation(n,cancelledReservationId);if(r.status!=='cancelled')throw Error('취소된 예약의 빈자리만 제안할 수 있습니다.');const matches=waitlistMatches(n,{reservationId:r.id,serviceId:r.serviceId,staffId:r.staffId,startAt:r.startAt,endAt:r.endAt});if(!matches.some(x=>x.id===w.id))throw Error('이 대기 고객의 조건과 빈자리가 맞지 않습니다.');w.status='offered';w.offer={slotStart:r.startAt,slotEnd:r.endAt,staffId:r.staffId,cancelledReservationId:r.id,sentAt:n.simulatedNow,expiresAt:addMinutes(n.simulatedNow,n.policy.offerHoldMin),status:'open'};audit(n,'offer',w.id,`취소 빈자리를 모의 제안했습니다. ${n.policy.offerHoldMin}분 동안 홀드합니다.`);return n;}
export function acceptOffer(state:AppState,waitId:string){let n=expireOffers(state);n.revision+=1;const w=n.waitlist.find(x=>x.id===waitId);if(!w||w.status!=='offered'||!w.offer||w.offer.status!=='open')throw Error('수락할 수 있는 제안이 없습니다.');const draft:ReservationDraft={customerId:w.customerId,serviceId:w.serviceId,staffId:w.offer.staffId,startAt:w.offer.slotStart,source:'waitlist',note:'취소 빈자리 대기자 회복 예약'};const check=bookingCheck(n,draft);if(!check.ok)throw Error(check.reasons.join(' '));const svc=getService(n,w.serviceId);const needsDeposit=n.policy.requireDeposit&&svc.deposit>0;const rid=id('RSV');n.reservations.unshift({id:rid,customerId:w.customerId,serviceId:w.serviceId,staffId:w.offer.staffId,startAt:w.offer.slotStart,endAt:w.offer.slotEnd,status:needsDeposit?'requested':'confirmed',depositStatus:needsDeposit?'unpaid':'not_required',depositAmount:n.policy.requireDeposit?svc.deposit:0,createdAt:n.simulatedNow,source:'waitlist',note:'대기자 빈자리 회복',recoveredFromReservationId:w.offer.cancelledReservationId,waitlistId:w.id});w.status='booked';w.offer.status='accepted';audit(n,'offer',w.id,needsDeposit?'제안한 빈자리를 수락해 예약 요청을 만들었습니다. 예약금 모의 결제 후 확정하세요.':'제안한 빈자리를 수락해 모의 예약을 확정했습니다.');return n;}
export function declineOffer(state:AppState,waitId:string){const n=next(state);const w=n.waitlist.find(x=>x.id===waitId);if(!w||w.status!=='offered'||!w.offer)throw Error('거절할 제안이 없습니다.');w.offer.status='declined';w.status='waiting';audit(n,'offer',w.id,'빈자리 제안을 거절하고 대기 상태로 되돌렸습니다.');return n;}
export function expireOffers(state:AppState){const n=structuredClone(state);let changed=false;for(const w of n.waitlist){if(w.status==='offered'&&offerExpired(w,n.simulatedNow)&&w.offer){w.offer.status='expired';w.status='waiting';audit(n,'offer',w.id,'제안 유효 시간이 지나 대기 상태로 되돌렸습니다.');changed=true;}}if(changed)n.revision+=1;return n;}
export function changeClock(state:AppState,iso:string){const n=next(state);if(Number.isNaN(new Date(iso).getTime()))throw Error('실습 시간을 확인하세요.');n.simulatedNow=new Date(iso).toISOString();audit(n,'system','clock','실습 시간을 변경했습니다.');return expireOffers(n);}
export function updatePolicy(state:AppState,patch:Partial<AppState['policy']>){const n=next(state);const merged={...n.policy,...patch};const problems=policyProblems(merged);if(problems.length)throw Error(problems.map(x=>x.message).join(' '));n.policy=merged;audit(n,'policy','policy','예약·취소 정책을 변경했습니다.');return n;}
export function addCustomer(state:AppState,input:{name:string;phone:string;email:string;notes?:string}){const n=next(state);if(!input.name.trim())throw Error('고객 이름을 입력하세요.');const cid=id('CUS');n.customers.unshift({id:cid,name:input.name.trim(),phone:input.phone.trim(),email:input.email.trim(),notes:input.notes?.trim()??'',visitCount:0,noShowCount:0});audit(n,'system',cid,'고객을 등록했습니다.');return n;}
