const test=require('node:test');const assert=require('node:assert/strict');
const {makeSeed}=require('../.test-build/src/data/seed.js');
const rules=require('../.test-build/src/domain/rules.js');
const eng=require('../.test-build/src/domain/engine.js');
const {metrics}=require('../.test-build/src/domain/metrics.js');
const csv=require('../.test-build/src/lib/csv.js');
const {LocalRepository,STORAGE_KEY}=require('../.test-build/src/lib/repository.js');
const {parseBackup}=require('../.test-build/src/domain/validation.js');
const base=new Date(2026,8,29,8,0,0);const seed=()=>makeSeed(base);

test('seed has business data',()=>{const s=seed();assert.equal(s.services.length,3);assert.equal(s.staff.length,2);assert.equal(s.customers.length,8);assert.equal(s.reservations.length,8);assert.equal(s.waitlist.length,3)});
test('seed clock is deterministic around noon',()=>{const s=seed();assert.equal(new Date(s.simulatedNow).getHours(),12)});
test('cancelled reservation does not occupy slot',()=>{const s=seed();const r=s.reservations.find(x=>x.id==='RSV-1005');const c=rules.bookingCheck(s,{customerId:'CUS-006',serviceId:r.serviceId,staffId:r.staffId,startAt:r.startAt});assert.equal(c.ok,true)});
test('confirmed reservation blocks overlap',()=>{const s=seed();const r=s.reservations.find(x=>x.id==='RSV-1003');const c=rules.bookingCheck(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:r.staffId,startAt:r.startAt});assert.equal(c.ok,false);assert.match(c.reasons.join(' '),/겹칩니다/)});
test('staff capability is checked',()=>{const s=seed();s.staff.find(x=>x.id==='ST-B').serviceIds=['SVC-CUT'];const c=rules.bookingCheck(s,{customerId:'CUS-001',serviceId:'SVC-COLOR',staffId:'ST-B',startAt:new Date(2026,8,30,15).toISOString()});assert.equal(c.ok,false)});
test('business hours are checked',()=>{const s=seed();const c=rules.bookingCheck(s,{customerId:'CUS-001',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,29,20).toISOString()});assert.equal(c.ok,false)});
test('create reservation starts requested with unpaid deposit',()=>{let s=seed();s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});const r=s.reservations[0];assert.equal(r.status,'requested');assert.equal(r.depositStatus,'unpaid');assert.equal(r.depositAmount,10000)});
test('confirm before deposit is rejected',()=>{let s=seed();s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});assert.throws(()=>eng.confirmReservation(s,s.reservations[0].id),/예약금/)});
test('pay deposit then confirm works',()=>{let s=seed();s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});const id=s.reservations[0].id;s=eng.payDeposit(s,id);s=eng.confirmReservation(s,id);assert.equal(s.reservations.find(x=>x.id===id).status,'confirmed')});
test('deposit not required policy creates not_required',()=>{let s=seed();s.policy.requireDeposit=false;s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});assert.equal(s.reservations[0].depositStatus,'not_required')});
test('early cancellation refunds paid deposit',()=>{let s=seed();const id='RSV-1008';s=eng.cancelReservation(s,id,'일정 변경');const r=s.reservations.find(x=>x.id===id);assert.equal(r.status,'cancelled');assert.equal(r.depositStatus,'refunded')});
test('late cancellation forfeits paid deposit',()=>{let s=seed();s.policy.cancellationHours=48;s=eng.cancelReservation(s,'RSV-1006','당일 취소');assert.equal(s.reservations.find(x=>x.id==='RSV-1006').depositStatus,'forfeited')});
test('cancelled reservation cannot be cancelled twice',()=>{let s=seed();assert.throws(()=>eng.cancelReservation(s,'RSV-1005','again'),/종료된 예약/)});
test('arrival only from confirmed',()=>{let s=seed();s=eng.markArrived(s,'RSV-1006');assert.equal(s.reservations.find(x=>x.id==='RSV-1006').status,'arrived');assert.throws(()=>eng.markArrived(s,'RSV-1004'))});
test('complete increments customer visits',()=>{let s=seed();const before=s.customers.find(x=>x.id==='CUS-007').visitCount;s=eng.completeReservation(s,'RSV-1006');assert.equal(s.customers.find(x=>x.id==='CUS-007').visitCount,before+1)});
test('no-show is allowed after grace',()=>{let s=seed();s=eng.markNoShow(s,'RSV-1002');const r=s.reservations.find(x=>x.id==='RSV-1002');assert.equal(r.status,'no_show');assert.equal(r.depositStatus,'forfeited');assert.equal(s.customers.find(x=>x.id==='CUS-002').noShowCount,2)});
test('no-show before grace is rejected',()=>{let s=seed();s=eng.changeClock(s,new Date(2026,8,29,10,35).toISOString());assert.throws(()=>eng.markNoShow(s,'RSV-1002'),/10분/)});
test('cancelled slot has two matching waiters',()=>{const s=seed(),r=s.reservations.find(x=>x.id==='RSV-1005');const m=rules.waitlistMatches(s,{reservationId:r.id,serviceId:r.serviceId,staffId:r.staffId,startAt:r.startAt,endAt:r.endAt});assert.equal(m.length,2)});
test('waitlist offer changes status and sets expiry',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const w=s.waitlist.find(x=>x.id==='WAIT-001');assert.equal(w.status,'offered');assert.equal(w.offer.status,'open');assert.ok(new Date(w.offer.expiresAt)>new Date(w.offer.sentAt))});
test('nonmatching waiter cannot receive slot',()=>{const s=seed();assert.throws(()=>eng.offerCancelledSlot(s,'WAIT-003','RSV-1005'),/맞지 않습니다/)});
test('accept offer creates a recovered reservation (requested + unpaid while a deposit is owed)',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const before=s.reservations.length;s=eng.acceptOffer(s,'WAIT-001');assert.equal(s.reservations.length,before+1);assert.equal(s.reservations[0].source,'waitlist');assert.equal(s.reservations[0].status,'requested');assert.equal(s.reservations[0].depositStatus,'unpaid');assert.equal(s.waitlist.find(x=>x.id==='WAIT-001').status,'booked')});
test('decline offer returns waiter to waiting',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');s=eng.declineOffer(s,'WAIT-001');assert.equal(s.waitlist.find(x=>x.id==='WAIT-001').status,'waiting')});
test('offer expires when clock passes hold',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const expiry=s.waitlist.find(x=>x.id==='WAIT-001').offer.expiresAt;s=eng.changeClock(s,new Date(new Date(expiry).getTime()+60000).toISOString());const w=s.waitlist.find(x=>x.id==='WAIT-001');assert.equal(w.status,'waiting');assert.equal(w.offer.status,'expired')});
test('accepting stale offer after competing booking is blocked',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const slot=s.reservations.find(x=>x.id==='RSV-1005').startAt;s=eng.createReservation(s,{customerId:'CUS-008',serviceId:'SVC-CUT',staffId:'ST-A',startAt:slot});const rid=s.reservations[0].id;s=eng.payDeposit(s,rid);s=eng.confirmReservation(s,rid);assert.throws(()=>eng.acceptOffer(s,'WAIT-001'),/겹칩니다/)});
test('add waitlist rejects reversed window',()=>{const s=seed();assert.throws(()=>eng.addWaitlist(s,{customerId:'CUS-001',serviceId:'SVC-CUT',staffId:null,windowStart:new Date(2026,8,30,15).toISOString(),windowEnd:new Date(2026,8,30,14).toISOString(),note:''}),/희망 시간/)});
test('add customer creates record',()=>{const s=eng.addCustomer(seed(),{name:'테스트 고객',phone:'010',email:'a@test'});assert.equal(s.customers[0].name,'테스트 고객')});
test('invalid policy hours rejected',()=>{const s=seed();assert.throws(()=>eng.updatePolicy(s,{openingHour:20,closingHour:19}),/영업 시작/)});
test('candidate slots return only free times',()=>{const s=seed();const d=rules.dayKey(s.simulatedNow);const slots=rules.candidateSlots(s,d,'ST-A','SVC-CUT');assert.ok(slots.length>0);assert.equal(slots.some(x=>x===s.reservations.find(r=>r.id==='RSV-1003').startAt),false)});
test('metrics count waiting and recovered',()=>{let s=seed();let m=metrics(s);assert.equal(m.waiting,3);assert.equal(m.recovered,0);s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');s=eng.acceptOffer(s,'WAIT-001');m=metrics(s);assert.ok(m.recovered>0)});
test('csv parser supports quoted commas',()=>{const rows=csv.parseCsv('id,name\n1,"Kim, Mina"\n');assert.equal(rows[1][1],'Kim, Mina')});
test('customer CSV detects duplicate id',()=>{const s=seed();const p=csv.previewCustomersCsv('id,name,phone,email\nCUS-001,dup,1,a@x\n',s);assert.equal(p.issues.length,1)});
test('valid customer CSV previews one row',()=>{const s=seed();const p=csv.previewCustomersCsv('id,name,phone,email\nCUS-900,새고객,010,a@x\n',s);assert.equal(p.issues.length,0);assert.equal(p.rows.length,1)});
test('reservation CSV detects overlap',()=>{const s=seed();const r=s.reservations.find(x=>x.id==='RSV-1003');const text=`id,customerId,serviceId,staffId,startAt,note\nRSV-X,CUS-006,SVC-CUT,ST-A,${r.startAt},x\n`;const p=csv.previewReservationsCsv(text,s);assert.equal(p.issues.length,1)});
test('reservation CSV accepts free slot',()=>{const s=seed();const text=`id,customerId,serviceId,staffId,startAt,note\nRSV-X,CUS-006,SVC-CUT,ST-B,${new Date(2026,8,30,17).toISOString()},x\n`;const p=csv.previewReservationsCsv(text,s);assert.equal(p.issues.length,0);assert.equal(p.rows[0].status,'requested')});
test('imported customers are appended',()=>{const s=seed();const p=csv.previewCustomersCsv('id,name,phone,email\nCUS-900,새고객,010,a@x\n',s);const n=csv.applyImportedCustomers(s,p.rows);assert.equal(n.customers.length,s.customers.length+1)});
test('backup parser roundtrips valid state',()=>{const s=seed();const p=parseBackup(JSON.stringify(s));assert.equal(p.reservations.length,s.reservations.length)});
test('backup parser rejects wrong schema',()=>{const s=seed();s.schemaVersion=2;assert.throws(()=>parseBackup(JSON.stringify(s)),/지원하지 않는/)});
test('repository session mode works without storage',()=>{const repo=new LocalRepository(null);const r=repo.load();assert.equal(r.mode,'session');repo.save(r.state)});
test('repository detects concurrent changes',()=>{const mem=new Map();const storage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};const repo=new LocalRepository(storage);const loaded=repo.load();mem.set(STORAGE_KEY,'other');assert.throws(()=>repo.save(loaded.state),/다른 탭/)});
test('repository replace keeps old data on quota failure',()=>{let old='';const storage={getItem:()=>old,setItem:(k,v)=>{if(v.length>20000)throw Error('quota');old=v},removeItem:()=>{}};const repo=new LocalRepository(storage);const initial=repo.load();repo.save(initial.state);const before=old;const big=structuredClone(initial.state);for(let i=0;i<200;i++)big.audit.push({id:'X'+i,at:big.simulatedNow,type:'system',entityId:'x',message:'x'.repeat(50)});assert.throws(()=>repo.replace(big),/저장 공간/);assert.equal(old,before)});
test('audit is written for state changes',()=>{let s=seed();const before=s.audit.length;s=eng.payDeposit(s,'RSV-1004');assert.equal(s.audit.length,before+1)});

// ---- P0-1 regression: policy values are validated in the engine, the Policies screen, restore and localStorage loading.
// Before the fix slotMinutes <= 0 was saved as-is and rules.candidateSlots looped forever (froze the schedule screen).
const polMod=require('../.test-build/src/domain/policy.js');const vld=require('../.test-build/src/domain/validation.js');
const {spawnSync}=require('node:child_process');const nodePath=require('node:path');
const BUILD=nodePath.resolve(__dirname,'../.test-build/src').replace(/\\/g,'/');
// Risky cases run in a child process with a timeout so a regression fails the test instead of hanging the whole test run.
const isolated=code=>{const r=spawnSync(process.execPath,['-e',`const B='${BUILD}/';const {makeSeed}=require(B+'data/seed.js');const rules=require(B+'domain/rules.js');const vld=require(B+'domain/validation.js');const seed=()=>makeSeed(new Date(2026,8,29,8,0,0));${code}`],{timeout:8000,encoding:'utf8'});return {hung:!!r.error,status:r.status,out:(r.stdout||'').trim(),err:(r.stderr||'').trim()};};
const memStore=raw=>{let v=raw;return{getItem:()=>v,setItem:(k,x)=>{v=x},removeItem:()=>{v=null}}};
const rejectPolicy=(patch,re)=>assert.throws(()=>eng.updatePolicy(seed(),patch),re);
const DEFAULT_SLOT_COUNT=7; // free 30-minute start times of ST-A / SVC-CUT on the seed day

test('policy: slotMinutes = 0 is rejected and the state is untouched',()=>{const s=seed();const before=JSON.stringify(s);rejectPolicy({slotMinutes:0},/기본 슬롯/);assert.throws(()=>eng.updatePolicy(s,{slotMinutes:0}),/기본 슬롯/);assert.equal(JSON.stringify(s),before)});
test('policy: negative slotMinutes is rejected',()=>{rejectPolicy({slotMinutes:-1},/기본 슬롯/);rejectPolicy({slotMinutes:-30},/기본 슬롯/)});
test('policy: NaN / Infinity / non-number slotMinutes is rejected',()=>{for(const v of [NaN,Infinity,-Infinity,null,undefined,'30','abc'])rejectPolicy({slotMinutes:v},/기본 슬롯/)});
test('policy: too small, too large or fractional slotMinutes is rejected',()=>{for(const v of [1,4,241,1e9,1e-9,7.5])rejectPolicy({slotMinutes:v},/기본 슬롯/)});
test('policy: invalid opening/closing hours are rejected',()=>{rejectPolicy({openingHour:-1},/영업 시작 시/);rejectPolicy({openingHour:24},/영업 시작 시/);rejectPolicy({closingHour:0},/영업 종료 시/);rejectPolicy({closingHour:25},/영업 종료 시/);rejectPolicy({openingHour:9.5},/영업 시작 시/);rejectPolicy({closingHour:NaN},/영업 종료 시/);rejectPolicy({openingHour:Infinity},/영업 시작 시/);rejectPolicy({openingHour:19,closingHour:9},/영업 시작 시간은 종료 시간보다 빨라야/);rejectPolicy({openingHour:10,closingHour:10},/영업 시작 시간은 종료 시간보다 빨라야/)});
test('policy: negative or non-finite cancellationHours is rejected, zero is allowed',()=>{for(const v of [-1,-0.5,NaN,Infinity,'24',8761])rejectPolicy({cancellationHours:v},/취소 기준 시간/);assert.equal(eng.updatePolicy(seed(),{cancellationHours:0}).policy.cancellationHours,0)});
test('policy: negative or non-finite noShowGraceMin is rejected, zero is allowed',()=>{for(const v of [-1,-30,NaN,Infinity,'10',1441])rejectPolicy({noShowGraceMin:v},/노쇼 유예/);assert.equal(eng.updatePolicy(seed(),{noShowGraceMin:0}).policy.noShowGraceMin,0)});
test('policy: offerHoldMin must be a positive finite number (0 is rejected)',()=>{for(const v of [0,-1,-20,NaN,Infinity,'20',10081])rejectPolicy({offerHoldMin:v},/제안 홀드/);assert.equal(eng.updatePolicy(seed(),{offerHoldMin:0.5}).policy.offerHoldMin,0.5)});
test('policy: several problems are all reported in one message',()=>{try{eng.updatePolicy(seed(),{slotMinutes:0,offerHoldMin:0,cancellationHours:-1});assert.fail('should throw')}catch(e){assert.match(e.message,/기본 슬롯/);assert.match(e.message,/제안 홀드/);assert.match(e.message,/취소 기준 시간/)}});
test('policy: valid values are saved as before and slot calculation follows them',()=>{const s=seed();const before=rules.candidateSlots(s,rules.dayKey(s.simulatedNow),'ST-A','SVC-CUT');assert.equal(before.length,DEFAULT_SLOT_COUNT);const n=eng.updatePolicy(s,{slotMinutes:15,openingHour:10,closingHour:18,cancellationHours:12,noShowGraceMin:5,offerHoldMin:30});assert.deepEqual([n.policy.slotMinutes,n.policy.openingHour,n.policy.closingHour,n.policy.cancellationHours,n.policy.noShowGraceMin,n.policy.offerHoldMin],[15,10,18,12,5,30]);assert.equal(n.revision,s.revision+1);assert.equal(n.audit.length,s.audit.length+1);const slots=rules.candidateSlots(n,rules.dayKey(n.simulatedNow),'ST-A','SVC-CUT');assert.ok(slots.length>0);for(const x of slots){const d=new Date(x);assert.equal(d.getMinutes()%15,0);assert.ok(d.getHours()>=10);const e=new Date(rules.addMinutes(x,70));assert.ok(e.getHours()*60+e.getMinutes()<=18*60)}assert.ok(slots.length>before.length)});
test('policy: boundary values are accepted, one step outside is rejected',()=>{const ok={slotMinutes:5,openingHour:0,closingHour:24,cancellationHours:0,noShowGraceMin:0,offerHoldMin:10080};assert.deepEqual(polMod.policyProblems({...seed().policy,...ok}),[]);assert.equal(eng.updatePolicy(seed(),{slotMinutes:240,cancellationHours:8760,noShowGraceMin:1440,openingHour:23,closingHour:24}).policy.slotMinutes,240)});
test('policy: unchanged default seed policy is valid and matches the documented defaults',()=>{const p=seed().policy;assert.deepEqual(polMod.policyProblems(p),[]);for(const f of Object.keys(polMod.POLICY_DEFAULTS))assert.equal(p[f],polMod.POLICY_DEFAULTS[f],f)});
test('policy: updating unrelated fields still works with a valid policy',()=>{const n=eng.updatePolicy(seed(),{businessName:'새 이름',requireDeposit:false});assert.equal(n.policy.businessName,'새 이름');assert.equal(n.policy.requireDeposit,false);assert.equal(n.policy.slotMinutes,30)});
test('policyProblems reports each bad field and the hours order',()=>{const fields=polMod.policyProblems({slotMinutes:0,openingHour:20,closingHour:19,cancellationHours:-1,noShowGraceMin:-1,offerHoldMin:0}).map(x=>x.field).sort();assert.deepEqual(fields,['cancellationHours','hours','noShowGraceMin','offerHoldMin','slotMinutes']);assert.equal(polMod.policyProblems(null).length,6);assert.deepEqual(polMod.policyProblems(undefined).map(x=>x.field).sort(),['cancellationHours','closingHour','noShowGraceMin','offerHoldMin','openingHour','slotMinutes'])});
test('repairPolicy replaces only the invalid values and keeps everything else',()=>{const p={...seed().policy,slotMinutes:0,cancellationHours:12,noShowGraceMin:-1,businessName:'유지'};const r=polMod.repairPolicy(p);assert.equal(r.policy.slotMinutes,30);assert.equal(r.policy.cancellationHours,12);assert.equal(r.policy.noShowGraceMin,10);assert.equal(r.policy.businessName,'유지');assert.equal(r.fixes.length,2);assert.equal(polMod.repairPolicy(seed().policy).fixes.length,0)});
test('repairPolicy resets the whole opening range when the order is wrong',()=>{const r=polMod.repairPolicy({...seed().policy,openingHour:20,closingHour:19});assert.deepEqual([r.policy.openingHour,r.policy.closingHour],[9,19]);assert.equal(r.fixes.length,1)});

test('restore/load: backups with bad policy values load without hanging and are repaired with a notice and an audit entry',()=>{
  const r=isolated(`const cases=[{slotMinutes:0},{slotMinutes:-30},{slotMinutes:null},{slotMinutes:'abc'},{slotMinutes:1e-9},{slotMinutes:1e9},{openingHour:20,closingHour:19},{closingHour:1e9},{closingHour:null},{cancellationHours:-1},{noShowGraceMin:-5},{offerHoldMin:0},{slotMinutes:0,offerHoldMin:0,closingHour:-3}];const out=cases.map(c=>{const s=seed();s.policy={...s.policy,...c};const p=vld.parseBackupWithNotes(JSON.stringify(s));const slots=rules.candidateSlots(p.state,rules.dayKey(p.state.simulatedNow),'ST-A','SVC-CUT');return{notes:p.notes.length,slots:slots.length,slot:p.state.policy.slotMinutes,name:p.state.policy.businessName,audit:p.state.audit[0].type+':'+p.state.audit[0].message.includes('기본값'),res:p.state.reservations.length}});console.log(JSON.stringify(out));`);
  assert.equal(r.hung,false,'loading a backup with a bad policy must not hang');assert.equal(r.status,0,r.err);const out=JSON.parse(r.out);assert.equal(out.length,13);for(const o of out){assert.equal(o.notes,1);assert.equal(o.slots,DEFAULT_SLOT_COUNT);assert.equal(o.name,seed().policy.businessName);assert.equal(o.audit,'policy:true');assert.equal(o.res,8)}});
test('restore: a repaired backup keeps all other data and the resulting policy is valid',()=>{const s=seed();s.policy={...s.policy,slotMinutes:0,cancellationHours:-2};const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.deepEqual(polMod.policyProblems(p.state.policy),[]);assert.equal(p.state.policy.cancellationHours,24);assert.equal(p.state.reservations.length,s.reservations.length);assert.equal(p.state.customers.length,s.customers.length);assert.equal(p.state.waitlist.length,s.waitlist.length);assert.equal(p.state.audit.length,s.audit.length+1);assert.match(p.notes[0],/기본 슬롯\(분\) 0 → 30/);assert.match(p.notes[0],/취소 기준 시간 -2 → 24/)});
test('restore: a valid backup produces no notes and no extra audit entry',()=>{const s=seed();const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.deepEqual(p.notes,[]);assert.equal(p.state.audit.length,s.audit.length);assert.deepEqual(vld.parseBackup(JSON.stringify(s)).policy,s.policy)});
test('restore: a policy object without the numeric fields is repaired, unknown fields are kept',()=>{const s=seed();s.policy={hello:1};const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.equal(p.state.policy.hello,1);for(const f of Object.keys(polMod.POLICY_DEFAULTS))assert.equal(p.state.policy[f],polMod.POLICY_DEFAULTS[f])});
test('restore: the audit log stays within the load-time limit after a repair',()=>{const s=seed();s.policy.slotMinutes=0;s.audit=Array.from({length:10000},(_,i)=>({id:'A'+i,at:s.simulatedNow,type:'system',entityId:'x',message:'m'}));const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.equal(p.state.audit.length,10000);assert.doesNotThrow(()=>vld.parseState(p.state))});
test('localStorage load: a stored state with a bad policy loads in normal mode with a notice, keeps the raw original and does not hang',()=>{
  const s=seed();s.policy={...s.policy,slotMinutes:0,offerHoldMin:-4};const raw=JSON.stringify(s);const st=memStore(raw);const repo=new LocalRepository(st);const t0=Date.now();const loaded=repo.load();assert.ok(Date.now()-t0<2000);assert.equal(loaded.mode,'persistent');assert.match(loaded.notice,/정책 값이 올바르지 않아 기본값으로 바꿨습니다/);assert.match(loaded.notice,/기본 슬롯\(분\) 0 → 30/);assert.match(loaded.notice,/저장된 원본은 그대로/);assert.deepEqual(polMod.policyProblems(loaded.state.policy),[]);assert.equal(loaded.state.reservations.length,s.reservations.length);assert.equal(repo.raw(),raw,'the stored original is not overwritten by loading');
  const slots=rules.candidateSlots(loaded.state,rules.dayKey(loaded.state.simulatedNow),'ST-A','SVC-CUT');assert.equal(slots.length,DEFAULT_SLOT_COUNT);
  repo.save(eng.payDeposit(loaded.state,'RSV-1004'));assert.deepEqual(polMod.policyProblems(JSON.parse(st.getItem(STORAGE_KEY)).policy),[]);const again=new LocalRepository(st).load();assert.equal(again.notice,'');assert.equal(again.mode,'persistent')});
test('localStorage load: a valid stored state loads with no notice',()=>{const st=memStore(JSON.stringify(seed()));const l=new LocalRepository(st).load();assert.equal(l.mode,'persistent');assert.equal(l.notice,'')});
test('repository.replace persists a repaired policy, never the bad one',()=>{const st=memStore(null);const repo=new LocalRepository(st);repo.load();const bad=seed();bad.policy={...bad.policy,slotMinutes:-30,closingHour:1e9};repo.replace(bad);assert.deepEqual(polMod.policyProblems(JSON.parse(st.getItem(STORAGE_KEY)).policy),[])});
test('candidateSlots never loops forever, even if a bad policy reaches memory directly',()=>{
  const r=isolated(`const one=(patch)=>{const s=seed();Object.assign(s.policy,patch);return rules.candidateSlots(s,rules.dayKey(s.simulatedNow),'ST-A','SVC-CUT').length;};const out=[{slotMinutes:0},{slotMinutes:-30},{slotMinutes:NaN},{slotMinutes:1e-9},{slotMinutes:Infinity},{slotMinutes:'x'},{closingHour:1e9},{openingHour:NaN},{openingHour:20,closingHour:19}].map(one);console.log(JSON.stringify(out));`);
  // Reversed hours only reach memory by bypassing every validation path; bookingCheck then rejects every candidate, so the result is an empty list - but never a hang.
  assert.equal(r.hung,false,'candidateSlots must not hang');assert.equal(r.status,0,r.err);assert.deepEqual(JSON.parse(r.out),[...new Array(8).fill(DEFAULT_SLOT_COUNT),0])});

// ---- P0 restore regression: backups are fully validated before anything is stored; the restore needs a preview and the typed confirmation word.
const bk=require('../.test-build/src/domain/backup.js');
const inspect=x=>bk.inspectBackup(typeof x==='string'?x:JSON.stringify(x));
const errorText=x=>inspect(x).errors.join('\n');
const mutated=fn=>{const s=seed();fn(s);return s};
const withOffer=()=>eng.offerCancelledSlot(seed(),'WAIT-001','RSV-1005');
const isoAt=(d,h,m=0)=>new Date(2026,8,d,h,m).toISOString();
const countingStore=raw=>{let v=raw;const c={get:0,set:0,remove:0};return{c,getItem:()=>{c.get++;return v},setItem:(k,x)=>{c.set++;v=x},removeItem:()=>{c.remove++;v=null}}};
const quotaStore=(limit,initial)=>{let v=initial;return{getItem:()=>v,setItem:(k,x)=>{if(x.length>limit)throw Error('QuotaExceededError');v=x},removeItem:()=>{v=null}}};
const bigValid=()=>{const s=seed();for(let i=0;i<60;i++)s.audit.push({id:'BIG-'+i,at:s.simulatedNow,type:'system',entityId:'x',message:'m'.repeat(200)});return s};

test('backup: a valid backup passes and comes out identical (only known fields, freshly built)',()=>{const r=inspect(seed());assert.equal(r.ok,true,r.errors.join('\n'));assert.equal(r.totalErrors,0);assert.deepEqual(r.notes,[]);assert.deepEqual(r.state,seed());assert.equal(bk.validateState(seed()).ok,true)});
test('backup: valid backup restores end to end and survives a reload',()=>{const st=memStore(JSON.stringify(seed()));const repo=new LocalRepository(st);repo.load();const other=seed();other.customers.push({id:'CUS-NEW',name:'새 고객',phone:'',email:'',notes:'',visitCount:0,noShowCount:0});const r=inspect(other);assert.equal(r.ok,true);repo.replace(r.state);const again=new LocalRepository(st).load();assert.equal(again.mode,'persistent');assert.equal(again.state.customers.length,9);assert.deepEqual(again.state,r.state)});
test('backup: states produced by every engine command and the CSV import are accepted (no false rejections of the app\'s own backups)',()=>{
  const steps=[s=>eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-B',startAt:isoAt(30,17)}),s=>eng.payDeposit(s,s.reservations[0].id),s=>eng.confirmReservation(s,s.reservations[0].id),s=>eng.markArrived(s,'RSV-1006'),s=>eng.completeReservation(s,'RSV-1006'),s=>eng.cancelReservation(s,'RSV-1008','x'),s=>eng.offerCancelledSlot(s,'WAIT-001','RSV-1005'),s=>eng.declineOffer(s,'WAIT-001'),s=>eng.offerCancelledSlot(s,'WAIT-002','RSV-1005'),s=>eng.acceptOffer(s,'WAIT-002'),s=>eng.offerCancelledSlot(s,'WAIT-001','RSV-1005'),s=>eng.addCustomer(s,{name:'새고객',phone:'',email:''}),s=>eng.addWaitlist(s,{customerId:'CUS-001',serviceId:'SVC-CUT',staffId:null,windowStart:isoAt(30,9),windowEnd:isoAt(30,12),note:''}),s=>eng.updatePolicy(s,{slotMinutes:15,requireDeposit:false,businessName:''}),s=>eng.changeClock(s,isoAt(29,18)),s=>eng.markNoShow(s,'RSV-1002'),
  s=>csv.applyImportedCustomers(s,csv.previewCustomersCsv('id,name,phone,email,notes,visitCount,noShowCount\nC-9,고객,1,a@x,,-5,2.7\n',s).rows),s=>{const t=Date.now();while(Date.now()===t){}/* CSV audit ids are AUD-<millisecond>; a human cannot import twice within one ms */return csv.applyImportedReservations(s,csv.previewReservationsCsv(`id,customerId,serviceId,staffId,startAt,note\nR-9,CUS-006,SVC-CARE,ST-A,${isoAt(31,10)},x\n`,s).rows)}];
  let s=seed();steps.forEach((step,i)=>{s=step(s);const r=inspect(s);assert.equal(r.ok,true,`step ${i+1}: ${r.errors.join(' | ')}`)});assert.ok(s.reservations.some(r=>r.source==='waitlist'&&r.recoveredFromReservationId==='RSV-1005'));assert.ok(s.waitlist.some(w=>w.offer&&w.offer.status==='expired'))});
test('backup: seed offers in every state are accepted',()=>{const s=withOffer();assert.equal(inspect(s).ok,true);const d=eng.declineOffer(s,'WAIT-001');assert.equal(inspect(d).ok,true);const a=eng.acceptOffer(withOffer(),'WAIT-001');assert.equal(inspect(a).ok,true)});

test('backup: status values that are not allowed are rejected',()=>{
  const cases=[[s=>{s.reservations[0].status='banana'},/status 값 "banana"/],[s=>{s.reservations[0].depositStatus='free'},/depositStatus 값 "free"/],[s=>{s.reservations[0].source='alien'},/source 값 "alien"/],[s=>{s.waitlist[0].status='gone'},/status 값 "gone"/],[s=>{s.audit[0].type='hack'},/type 값 "hack"/],[s=>{s.reservations[0].status=7},/status 값 7/],[s=>{s.reservations[0].status=''},/status 값 ""/]];
  for(const [fn,re] of cases){const r=inspect(mutated(fn));assert.equal(r.ok,false);assert.match(r.errors.join('\n'),re);assert.match(r.errors.join('\n'),/허용되지 않습니다/)}
  const o=withOffer();o.waitlist.find(w=>w.id==='WAIT-001').offer.status='weird';assert.match(errorText(o),/status 값 "weird"/)});
test('backup: missing required fields are rejected',()=>{
  const cases=[[s=>{delete s.reservations[0].customerId},/customerId는 문자열/],[s=>{delete s.reservations[0].startAt},/startAt는 실제로 존재하는 시각/],[s=>{delete s.customers[0].name},/name는 문자열/],[s=>{delete s.services[0].price},/price는 유한한 숫자/],[s=>{delete s.staff[0].serviceIds},/serviceIds는 배열/],[s=>{delete s.waitlist[0].staffId},/staffId는 문자열/],[s=>{delete s.policy.businessName},/businessName는 문자열/],[s=>{delete s.policy.requireDeposit},/requireDeposit는 true 또는 false/],[s=>{delete s.revision},/revision는 유한한 숫자/],[s=>{delete s.simulatedNow},/simulatedNow는 실제로 존재하는 시각/],[s=>{delete s.schemaVersion},/schemaVersion/],[s=>{delete s.reservations[0].id},/id가 비어|id는 문자열/],[s=>{delete s.audit[0].message},/message는 문자열/],[s=>{delete s.services},/서비스 목록이 배열이 아닙니다/],[s=>{delete s.policy},/정책\(policy\)이 객체가 아닙니다/]];
  for(const [fn,re] of cases){const r=inspect(mutated(fn));assert.equal(r.ok,false,String(re));assert.match(r.errors.join('\n'),re)}});
test('backup: wrong types are rejected',()=>{
  const cases=[[s=>{s.reservations[0].startAt=123},/startAt는 실제로 존재하는 시각/],[s=>{s.reservations[0].depositAmount='10000'},/depositAmount는 유한한 숫자/],[s=>{s.services[0].active='yes'},/active는 true 또는 false/],[s=>{s.services={}},/서비스 목록이 배열이 아닙니다/],[s=>{s.customers[0].visitCount='x'},/visitCount는 유한한 숫자/],[s=>{s.reservations[0]='text'},/객체가 아닙니다/],[s=>{s.staff[0].serviceIds='SVC-CUT'},/serviceIds는 배열/],[s=>{s.customers[0].name=42},/name는 문자열/],[s=>{s.reservations[0].depositAmount=-1},/depositAmount는 0 이상/],[s=>{s.services[0].durationMin=0},/durationMin는 1 이상/],[s=>{s.revision=1.5},/revision는 정수/],[s=>{s.policy.requireDeposit='true'},/requireDeposit는 true 또는 false/],[s=>{s.waitlist[0].note=null},/note는 문자열/],[s=>{s.reservations[0].note='x'.repeat(5001)},/note가 너무 깁니다/]];
  for(const [fn,re] of cases){const r=inspect(mutated(fn));assert.equal(r.ok,false,String(re));assert.match(r.errors.join('\n'),re)}
  for(const top of ['[]','null','"text"','123','true'])assert.match(errorText(top),/객체가 아닙니다/)});
test('backup: unsupported schema versions are rejected',()=>{for(const v of [0,2,'1',null])assert.match(errorText(mutated(s=>{s.schemaVersion=v})),/지원하지 않는 백업 버전/)});
test('backup: duplicate IDs are rejected in every collection',()=>{
  const dup=(key,label,idOf)=>{const s=seed();s[key].push(JSON.parse(JSON.stringify(s[key][0])));const r=inspect(s);assert.equal(r.ok,false,key);assert.match(r.errors.join('\n'),new RegExp(`${label} ID "${idOf(s[key][0])}"가 2번 중복됩니다`))};
  dup('customers','고객',x=>x.id);dup('services','서비스',x=>x.id);dup('staff','담당자',x=>x.id);dup('reservations','예약',x=>x.id);dup('waitlist','대기자',x=>x.id);dup('audit','감사 이력',x=>x.id);
  assert.match(errorText(mutated(s=>{s.customers.push({...s.customers[0]},{...s.customers[0]})})),/3번 중복/)});
test('backup: references to a customer that does not exist are rejected',()=>{assert.match(errorText(mutated(s=>{s.reservations[0].customerId='CUS-999'})),/예약 1번째 \(RSV-1001\): customerId "CUS-999"에 해당하는 고객/);assert.match(errorText(mutated(s=>{s.waitlist[0].customerId='CUS-999'})),/대기자 1번째 \(WAIT-001\): customerId "CUS-999"에 해당하는 고객/)});
test('backup: references to a service that does not exist are rejected',()=>{assert.match(errorText(mutated(s=>{s.reservations[0].serviceId='SVC-X'})),/serviceId "SVC-X"에 해당하는 서비스/);assert.match(errorText(mutated(s=>{s.waitlist[0].serviceId='SVC-X'})),/대기자 1번째.*serviceId "SVC-X"/);assert.match(errorText(mutated(s=>{s.staff[0].serviceIds.push('SVC-X')})),/담당자 1번째 \(ST-A\): serviceIds "SVC-X"에 해당하는 서비스/)});
test('backup: references to a staff member that does not exist are rejected',()=>{assert.match(errorText(mutated(s=>{s.reservations[0].staffId='ST-Z'})),/staffId "ST-Z"에 해당하는 담당자/);assert.match(errorText(mutated(s=>{s.waitlist[0].staffId='ST-Z'})),/대기자 1번째.*staffId "ST-Z"/);const o=withOffer();o.waitlist.find(w=>w.id==='WAIT-001').offer.staffId='ST-Z';assert.match(errorText(o),/제안\(offer\).*staffId "ST-Z"/);assert.equal(inspect(mutated(s=>{s.waitlist[0].staffId=null})).ok,true)});
test('backup: broken reservation references are rejected (recovered-from, waitlist link, offer origin)',()=>{
  assert.match(errorText(mutated(s=>{s.reservations[0].recoveredFromReservationId='RSV-404'})),/recoveredFromReservationId "RSV-404"에 해당하는 원본 예약/);
  assert.match(errorText(mutated(s=>{s.reservations[0].recoveredFromReservationId='RSV-1001'})),/자기 자신/);
  assert.match(errorText(mutated(s=>{s.reservations[0].waitlistId='WAIT-404'})),/waitlistId "WAIT-404"에 해당하는 대기자/);
  const o=withOffer();o.waitlist.find(w=>w.id==='WAIT-001').offer.cancelledReservationId='RSV-404';assert.match(errorText(o),/제안\(offer\).*cancelledReservationId "RSV-404"에 해당하는 취소된 원본 예약/);
  const ok=mutated(s=>{s.reservations[0].recoveredFromReservationId='RSV-1005';s.reservations[0].waitlistId='WAIT-001'});assert.equal(inspect(ok).ok,true)});
test('backup: waitlist status and offer must agree',()=>{const a=mutated(s=>{s.waitlist[0].status='offered'});assert.match(errorText(a),/offered이면 상태가 open인 제안/);const b=withOffer();b.waitlist.find(w=>w.id==='WAIT-001').status='waiting';assert.match(errorText(b),/open이면 status는 offered/);const c=mutated(s=>{s.waitlist[0].status='booked'});assert.match(errorText(c),/booked이면 수락된/)});
test('backup: dates that do not exist are rejected, real ones are accepted',()=>{
  for(const bad of ['2026-02-30T10:00:00.000Z','2026-13-01T00:00:00.000Z','not-a-date','2026-09-29 10:00:00','2026-09-29T25:00:00.000Z','2026-09-29T10:61:00.000Z','2026-09-29T10:00:00','2026-02-29T00:00:00.000Z',20260929,null,'']){const r=inspect(mutated(s=>{s.reservations[0].startAt=bad}));assert.equal(r.ok,false,String(bad));assert.match(r.errors.join('\n'),/startAt는 실제로 존재하는 시각/)}
  for(const good of ['2026-09-29T10:00:00.000Z','2026-09-29T10:00:00Z','2026-09-29T19:00:00+09:00','2028-02-29T00:00:00.000Z']){assert.equal(inspect(mutated(s=>{s.reservations[0].startAt=good;s.reservations[0].endAt='2029-01-01T00:00:00.000Z'})).ok,true,good)}
  assert.match(errorText(mutated(s=>{s.simulatedNow='2026-99-99T00:00:00.000Z'})),/simulatedNow/);assert.match(errorText(mutated(s=>{s.audit[0].at='x'})),/감사 이력 1번째.*at는/);assert.match(errorText(mutated(s=>{s.reservations[4].cancelledAt='nope'})),/cancelledAt/);assert.match(errorText(mutated(s=>{s.reservations[0].createdAt=5})),/createdAt/);
  assert.match(errorText(mutated(s=>{s.reservations[0].endAt=s.reservations[0].startAt})),/endAt은 startAt보다 뒤/);assert.match(errorText(mutated(s=>{s.waitlist[0].windowEnd=s.waitlist[0].windowStart})),/windowEnd는 windowStart보다 뒤/);const o=withOffer();const w=o.waitlist.find(x=>x.id==='WAIT-001');w.offer.slotEnd=w.offer.slotStart;assert.match(errorText(o),/slotEnd는 slotStart보다 뒤/)});
test('backup: array size limits are enforced (and exactly the limit is accepted)',()=>{
  const fill=(key,n,make)=>{const s=seed();s[key]=Array.from({length:n},(_,i)=>make(s,i));return s};
  const cases=[['reservations',3001,(s,i)=>({...s.reservations[0],id:'R'+i}),/예약가 너무 많습니다: 3001개 \(최대 3000개\)/],['waitlist',3001,(s,i)=>({...s.waitlist[0],id:'W'+i}),/대기자가 너무 많습니다: 3001개 \(최대 3000개\)/],['audit',10001,(s,i)=>({...s.audit[0],id:'A'+i}),/감사 이력가 너무 많습니다: 10001개 \(최대 10000개\)/],['customers',5001,(s,i)=>({...s.customers[0],id:'C'+i}),/고객가 너무 많습니다: 5001개 \(최대 5000개\)/],['services',101,(s,i)=>({...s.services[0],id:'S'+i}),/서비스가 너무 많습니다: 101개 \(최대 100개\)/],['staff',101,(s,i)=>({...s.staff[0],id:'T'+i}),/담당자가 너무 많습니다: 101개 \(최대 100개\)/]];
  for(const [key,n,make,re] of cases){const r=inspect(fill(key,n,make));assert.equal(r.ok,false,key);assert.match(r.errors.join('\n'),re);assert.equal(r.totalErrors,1,`${key}: only the size error, no follow-up noise: ${r.errors.join(' | ')}`)}
  assert.equal(inspect(fill('reservations',3000,(s,i)=>({...s.reservations[0],id:'R'+i}))).ok,true);assert.equal(inspect(fill('audit',10000,(s,i)=>({...s.audit[0],id:'A'+i}))).ok,true);assert.equal(bk.BACKUP_LIMITS.reservations,3000)});
test('backup: file size limits, empty and broken files are rejected',()=>{
  assert.match(errorText('x'.repeat(vld.backupLimit()+1)),/너무 큽니다/);assert.match(errorText(''),/빈 파일/);assert.match(errorText('   \n'),/빈 파일/);assert.match(errorText('{'),/JSON 문법/);assert.match(errorText('{"a":'),/JSON 문법/);assert.match(errorText(undefined),/읽지 못했습니다/);
  assert.equal(bk.backupTooLarge(bk.MAX_BACKUP_BYTES),false);assert.equal(bk.backupTooLarge(bk.MAX_BACKUP_BYTES+1),true);assert.equal(bk.MAX_BACKUP_BYTES,vld.backupLimit()*3)});
test('backup: problems are all listed (capped at 100) with the record they belong to',()=>{const r=inspect(mutated(s=>{s.reservations=Array.from({length:300},(_,i)=>({...s.reservations[0],id:'R'+i,status:'banana'}))}));assert.equal(r.ok,false);assert.equal(r.errors.length,100);assert.ok(r.totalErrors>=300);assert.match(r.errors[0],/예약 1번째 \(R0\)/);const multi=inspect(mutated(s=>{s.reservations[0].status='x';s.customers[0].name='';s.services[0].price=-1}));assert.equal(multi.totalErrors,3)});
test('backup: unknown fields are dropped and __proto__ tricks do nothing',()=>{const s=seed();s.extra={a:1};s.reservations[0].hack='x';const raw=JSON.stringify(s).replace('{"schemaVersion":1','{"__proto__":{"polluted":true},"schemaVersion":1');assert.ok(raw.includes('__proto__'));const r=inspect(raw);assert.equal(r.ok,true,r.errors.join('\n'));assert.equal('extra' in r.state,false);assert.equal('hack' in r.state.reservations[0],false);assert.equal({}.polluted,undefined);assert.equal(Object.prototype.polluted,undefined);assert.deepEqual(r.state,seed())});
test('backup: values the app itself can produce stay valid (negative CSV counts, empty business name)',()=>{const s=seed();s.customers[0].visitCount=-5;s.customers[0].noShowCount=2.7;s.policy.businessName='';assert.equal(inspect(s).ok,true)});

test('restore safety: a rejected backup never touches the stored data, even when it is passed straight to the repository',()=>{
  const good=seed();const raw=JSON.stringify(good);const st=countingStore(raw);const repo=new LocalRepository(st);repo.load();
  const bads=[mutated(s=>{s.reservations[0].status='banana'}),mutated(s=>{s.reservations[0].customerId='CUS-999'}),mutated(s=>{s.customers.push({...s.customers[0]})}),mutated(s=>{s.reservations[0].startAt='2026-02-30T00:00:00.000Z'}),mutated(s=>{delete s.policy}),{schemaVersion:1}];
  for(const bad of bads){const r=inspect(bad);assert.equal(r.ok,false);assert.equal(st.c.set,0,'inspecting must not write');assert.throws(()=>repo.replace(bad),/복원할 자료가 올바르지 않아 복원하지 않았습니다. 현재 자료는 바뀌지 않았습니다/);assert.equal(repo.raw(),raw)}
  assert.equal(st.c.set,0);assert.equal(st.c.remove,0);assert.deepEqual(new LocalRepository(st).load().state,good);repo.save(eng.payDeposit(good,'RSV-1004'));assert.equal(st.c.set,1)});
test('restore safety: a rejected backup keeps recovery mode and the unreadable original',()=>{const st=memStore('{broken');const repo=new LocalRepository(st);assert.equal(repo.load().mode,'recovery');assert.throws(()=>repo.replace(mutated(s=>{s.reservations[0].status='banana'})),/복원하지 않았습니다/);assert.equal(st.getItem(STORAGE_KEY),'{broken');assert.throws(()=>repo.save(seed()),/복구 모드/);repo.replace(seed());assert.equal(new LocalRepository(st).load().mode,'persistent')});
test('restore safety: a valid backup that does not fit in storage leaves the current data untouched',()=>{
  const cur=JSON.stringify(seed());const st=quotaStore(cur.length+500,cur);const repo=new LocalRepository(st);repo.load();const big=bigValid();assert.equal(inspect(big).ok,true);
  assert.throws(()=>repo.replace(big),/저장 공간이 부족하거나 권한이 없어 복원하지 못했습니다. 기존 자료는 유지됩니다/);assert.equal(st.getItem(STORAGE_KEY),cur);assert.deepEqual(new LocalRepository(st).load().state,seed());repo.save(eng.payDeposit(seed(),'RSV-1004'));assert.ok(st.getItem(STORAGE_KEY).length<=cur.length+500)});
test('restore safety: a failed write that clobbered the stored value is rolled back',()=>{const cur=JSON.stringify(seed());let v=cur,calls=0;const st={getItem:()=>v,setItem:(k,x)=>{calls++;if(calls===1){v=x.slice(0,15);throw Error('quota')}v=x},removeItem:()=>{v=null}};const repo=new LocalRepository(st);repo.load();assert.throws(()=>repo.replace(bigValid()),/복원하지 못했습니다/);assert.equal(v,cur)});
test('restore safety: the seed used by "reset" is always valid',()=>{assert.equal(inspect(seed()).ok,true);assert.equal(bk.validateState(makeSeedForReset()).ok,true)});
function makeSeedForReset(){return require('../.test-build/src/data/seed.js').makeSeed()}

test('restore policy: a backup where only policy numbers are unusable is repaired like P0-1, everything else is kept',()=>{
  const s=seed();s.policy={...s.policy,slotMinutes:0,offerHoldMin:-1,cancellationHours:NaN,openingHour:20,closingHour:19};const r=inspect(JSON.stringify(s));assert.equal(r.ok,true,r.errors.join('\n'));assert.equal(r.notes.length,1);assert.match(r.notes[0],/기본 슬롯\(분\) 0 → 30/);assert.match(r.notes[0],/빈자리 제안 홀드\(분\) -1 → 20/);assert.match(r.notes[0],/취소 기준 시간 없음 → 24/);assert.match(r.notes[0],/영업시간 20~19 → 9~19/);
  assert.deepEqual(polMod.policyProblems(r.state.policy),[]);const base=seed();assert.deepEqual(r.state.reservations,base.reservations);assert.deepEqual(r.state.customers,base.customers);assert.deepEqual(r.state.waitlist,base.waitlist);assert.deepEqual(r.state.services,base.services);assert.equal(r.state.audit.length,base.audit.length+1);assert.equal(r.state.audit[0].type,'policy');assert.equal(r.state.policy.businessName,base.policy.businessName);
  const st=memStore(JSON.stringify(seed()));const repo=new LocalRepository(st);repo.load();repo.replace(r.state);assert.deepEqual(polMod.policyProblems(JSON.parse(st.getItem(STORAGE_KEY)).policy),[]);assert.equal(new LocalRepository(st).load().notice,'')});
test('restore policy: a repaired policy does not hide other problems, and non-numeric policy fields are still errors',()=>{const both=seed();both.policy.slotMinutes=0;both.reservations[0].status='banana';const r=inspect(both);assert.equal(r.ok,false);assert.deepEqual(r.notes,[]);assert.match(r.errors.join('\n'),/status 값 "banana"/);assert.match(errorText(mutated(s=>{s.policy.requireDeposit='yes'})),/requireDeposit/);assert.equal(inspect(mutated(s=>{s.policy.slotMinutes=0})).ok,true)});
test('restore policy: repairing keeps the audit log within its limit',()=>{const s=seed();s.policy.slotMinutes=0;s.audit=Array.from({length:10000},(_,i)=>({...s.audit[0],id:'A'+i}));const r=inspect(s);assert.equal(r.ok,true);assert.equal(r.state.audit.length,10000);assert.equal(r.state.audit[0].type,'policy')});

test('restore confirmation: the final restore needs a valid backup AND the exact word',()=>{
  const ok=inspect(seed());assert.equal(bk.RESTORE_CONFIRM_TEXT,'복원');
  for(const typed of ['','복','복원 ',' 복원','복원복원','restore','RESTORE','복 원','복원\n','확인'])assert.equal(bk.canConfirmRestore(ok,typed),false,JSON.stringify(typed));
  assert.equal(bk.canConfirmRestore(ok,'복원'),true);
  const failed=inspect(mutated(s=>{s.reservations[0].status='banana'}));assert.equal(bk.canConfirmRestore(failed,'복원'),false);assert.equal(bk.canConfirmRestore(null,'복원'),false);assert.equal(bk.canConfirmRestore(undefined,'복원'),false);assert.equal(bk.canConfirmRestore({ok:true,errors:[],totalErrors:0,notes:[]},'복원'),false);
  const repaired=inspect(mutated(s=>{s.policy.slotMinutes=0}));assert.equal(bk.canConfirmRestore(repaired,''),false);assert.equal(bk.canConfirmRestore(repaired,'복원'),true)});

test('restore preview: summarizes what changes between the current data and the backup',()=>{
  const current=seed();const next=seed();next.reservations.push({...next.reservations[0],id:'RSV-NEW',status:'cancelled'});next.reservations=next.reservations.filter(r=>r.id!=='RSV-1008');next.customers.push({id:'CUS-NEW',name:'새 고객',phone:'',email:'',notes:'',visitCount:0,noShowCount:0});next.waitlist=next.waitlist.filter(w=>w.id!=='WAIT-003');next.policy.slotMinutes=15;next.policy.requireDeposit=false;next.policy.businessName='다른 점포';next.simulatedNow=isoAt(30,9);
  const sum=bk.describeRestore(current,next);const row=l=>sum.rows.find(r=>r.label===l);
  assert.deepEqual([row('고객').current,row('고객').next],[8,9]);assert.deepEqual([row('예약').current,row('예약').next],[8,8]);assert.deepEqual([row('대기자').current,row('대기자').next],[3,2]);
  assert.deepEqual(sum.onlyInCurrent.map(r=>[r.label,r.current]),[['고객',0],['예약',1],['대기자',1]]);assert.deepEqual(sum.onlyInBackup.map(r=>[r.label,r.next]),[['고객',1],['예약',1],['대기자',0]]);
  const cancelled=sum.reservationStatus.find(r=>r.label==='예약 취소');assert.deepEqual([cancelled.current,cancelled.next],[1,2]);
  assert.ok(sum.policyChanges.some(x=>/기본 슬롯\(분\) 30 → 15/.test(x)));assert.ok(sum.policyChanges.some(x=>/예약금 사용 켬 → 끔/.test(x)));assert.ok(sum.policyChanges.some(x=>/사업장 이름/.test(x)));assert.notEqual(sum.clock.current,sum.clock.next);
  const same=bk.describeRestore(seed(),seed());assert.deepEqual(same.policyChanges,[]);assert.deepEqual(same.onlyInCurrent.map(r=>r.current),[0,0,0]);assert.deepEqual(same.onlyInBackup.map(r=>r.next),[0,0,0])});
test('restore preview: a repaired policy is reported with the before/after values and shows up in the summary',()=>{const s=seed();s.policy.slotMinutes=0;const r=inspect(s);const sum=bk.describeRestore(seed(),r.state);assert.deepEqual(sum.policyChanges,[]);assert.match(r.notes[0],/기본 슬롯\(분\) 0 → 30/)});

// ---- P0-3 deposit integrity: the deposit requirement is fixed per reservation, deposits are never paid on closed reservations,
// ---- a no-show settles a paid deposit, a recovered reservation is not auto-paid, arrived cannot be cancelled and only confirmed can be a no-show.
const dRes=(s,id)=>s.reservations.find(r=>r.id===id);
const dPair=r=>[r.status,r.depositStatus];
const dBooking=s=>{const n=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-B',startAt:isoAt(30,17)});return {s:n,id:n.reservations[0].id}};

test('deposit: paying is rejected on a cancelled reservation',()=>{let s=seed();s=eng.cancelReservation(s,'RSV-1004','x');assert.deepEqual(dPair(dRes(s,'RSV-1004')),['cancelled','unpaid']);assert.throws(()=>eng.payDeposit(s,'RSV-1004'),/결제할 수 없습니다/)});
test('deposit: paying is rejected on a no_show reservation',()=>{let s=seed();s=eng.changeClock(s,isoAt(29,14));dRes(s,'RSV-1004').status='confirmed';s=eng.markNoShow(s,'RSV-1004');assert.deepEqual(dPair(dRes(s,'RSV-1004')),['no_show','unpaid']);assert.throws(()=>eng.payDeposit(s,'RSV-1004'),/결제할 수 없습니다/)});
test('deposit: paying is rejected on a completed reservation (legacy state that still owes a deposit)',()=>{const s=seed();dRes(s,'RSV-1001').depositStatus='unpaid';assert.equal(dRes(s,'RSV-1001').status,'completed');assert.throws(()=>eng.payDeposit(s,'RSV-1001'),/결제할 수 없습니다/)});
test('deposit: paying still works while requested, confirmed or arrived',()=>{let s=seed();s=eng.payDeposit(s,'RSV-1004');assert.deepEqual(dPair(dRes(s,'RSV-1004')),['requested','paid']);for(const status of ['confirmed','arrived']){const t=seed();const r=dRes(t,'RSV-1003');r.status=status;r.depositStatus='unpaid';assert.equal(dRes(eng.payDeposit(t,'RSV-1003'),'RSV-1003').depositStatus,'paid',status)}});
test('deposit: canPayDeposit is true only for a live reservation that still owes a deposit',()=>{const s=seed();assert.equal(rules.canPayDeposit(dRes(s,'RSV-1004')),true);for(const id of ['RSV-1001','RSV-1002','RSV-1003','RSV-1005'])assert.equal(rules.canPayDeposit(dRes(s,id)),false,id);const t=seed();for(const status of ['cancelled','completed','no_show']){dRes(t,'RSV-1004').status=status;assert.equal(rules.canPayDeposit(dRes(t,'RSV-1004')),false,status)}});

test('deposit: a no-show with forfeit OFF refunds the paid deposit and the audit entry says so',()=>{let s=seed();s=eng.updatePolicy(s,{noShowForfeit:false});s=eng.markNoShow(s,'RSV-1002');assert.deepEqual(dPair(dRes(s,'RSV-1002')),['no_show','refunded']);assert.equal(s.audit[0].type,'noshow');assert.match(s.audit[0].message,/모의 환불/)});
test('deposit: a no-show with forfeit ON forfeits the paid deposit and the audit entry says so',()=>{let s=seed();s=eng.markNoShow(s,'RSV-1002');assert.deepEqual(dPair(dRes(s,'RSV-1002')),['no_show','forfeited']);assert.equal(s.audit[0].type,'noshow');assert.match(s.audit[0].message,/모의 차감/)});

test('deposit: accepting an offer makes a requested + unpaid reservation when a deposit is required; it is confirmed only after a mock payment',()=>{
  let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const deposits=()=>s.audit.filter(a=>a.type==='deposit').length;const before=deposits();
  s=eng.acceptOffer(s,'WAIT-001');const r=s.reservations.find(x=>x.source==='waitlist');
  assert.deepEqual([r.status,r.depositStatus,r.depositAmount],['requested','unpaid',10000]);assert.equal(s.waitlist.find(w=>w.id==='WAIT-001').status,'booked');assert.equal(s.waitlist.find(w=>w.id==='WAIT-001').offer.status,'accepted');
  assert.equal(r.recoveredFromReservationId,'RSV-1005');assert.equal(r.waitlistId,'WAIT-001');assert.equal(deposits(),before,'no deposit event without a payment action');
  assert.throws(()=>eng.confirmReservation(s,r.id),/예약금 모의 결제/);
  s=eng.payDeposit(s,r.id);assert.equal(deposits(),before+1);s=eng.confirmReservation(s,r.id);assert.deepEqual(dPair(dRes(s,r.id)),['confirmed','paid'])});
test('deposit: the unpaid recovered reservation still occupies the slot',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');s=eng.acceptOffer(s,'WAIT-001');const r=s.reservations.find(x=>x.source==='waitlist');assert.equal(rules.bookingCheck(s,{customerId:'CUS-002',serviceId:'SVC-CUT',staffId:r.staffId,startAt:r.startAt}).ok,false)});
test('deposit: accepting an offer that needs no deposit confirms it at once (policy OFF, or service deposit 0)',()=>{
  let s=seed();s=eng.updatePolicy(s,{requireDeposit:false});s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');s=eng.acceptOffer(s,'WAIT-001');let r=s.reservations.find(x=>x.source==='waitlist');assert.deepEqual([r.status,r.depositStatus,r.depositAmount],['confirmed','not_required',0]);
  let t=seed();t.services.find(x=>x.id==='SVC-CUT').deposit=0;t=eng.offerCancelledSlot(t,'WAIT-001','RSV-1005');t=eng.acceptOffer(t,'WAIT-001');r=t.reservations.find(x=>x.source==='waitlist');assert.deepEqual([r.status,r.depositStatus,r.depositAmount],['confirmed','not_required',0])});

test('deposit: an arrived reservation cannot be cancelled (engine and decision helper)',()=>{let s=seed();s=eng.markArrived(s,'RSV-1006');assert.throws(()=>eng.cancelReservation(s,'RSV-1006','x'),/도착/);assert.equal(rules.cancellationDecision(s,dRes(s,'RSV-1006')).allowed,false);assert.deepEqual(dPair(dRes(s,'RSV-1006')),['arrived','paid'])});
test('deposit: requested and confirmed reservations are still cancellable with the same refund / forfeit / unpaid outcomes',()=>{let s=seed();s=eng.cancelReservation(s,'RSV-1008','x');assert.deepEqual(dPair(dRes(s,'RSV-1008')),['cancelled','refunded']);let t=seed();t.policy.cancellationHours=48;t=eng.cancelReservation(t,'RSV-1006','x');assert.deepEqual(dPair(dRes(t,'RSV-1006')),['cancelled','forfeited']);assert.deepEqual(dPair(dRes(eng.cancelReservation(seed(),'RSV-1004','x'),'RSV-1004')),['cancelled','unpaid'])});

test('deposit: a reservation made while a deposit was required still needs it after the global policy is switched OFF',()=>{let {s,id}=dBooking(seed());assert.deepEqual(dPair(dRes(s,id)),['requested','unpaid']);s=eng.updatePolicy(s,{requireDeposit:false});assert.throws(()=>eng.confirmReservation(s,id),/예약금 모의 결제/);s=eng.payDeposit(s,id);s=eng.confirmReservation(s,id);assert.deepEqual(dPair(dRes(s,id)),['confirmed','paid'])});
test('deposit: the seeded unpaid reservation keeps its requirement after the policy is switched OFF',()=>{const s=eng.updatePolicy(seed(),{requireDeposit:false});assert.throws(()=>eng.confirmReservation(s,'RSV-1004'),/예약금 모의 결제/)});
test('deposit: a reservation made while NO deposit was required stays deposit-free after the policy is switched ON',()=>{let s=eng.updatePolicy(seed(),{requireDeposit:false});let {s:t,id}=dBooking(s);assert.deepEqual([...dPair(dRes(t,id)),dRes(t,id).depositAmount],['requested','not_required',0]);t=eng.updatePolicy(t,{requireDeposit:true});t=eng.confirmReservation(t,id);assert.deepEqual(dPair(dRes(t,id)),['confirmed','not_required'])});
test('deposit: a CSV-imported reservation keeps the requirement it was created with',()=>{let s=seed();const p=csv.previewReservationsCsv(`id,customerId,serviceId,staffId,startAt,note\nR-9,CUS-006,SVC-CARE,ST-A,${isoAt(31,10)},x\n`,s);assert.equal(p.issues.length,0);s=csv.applyImportedReservations(s,p.rows);assert.deepEqual(dPair(dRes(s,'R-9')),['requested','unpaid']);s=eng.updatePolicy(s,{requireDeposit:false});assert.throws(()=>eng.confirmReservation(s,'R-9'),/예약금 모의 결제/)});
test('deposit: switching the global deposit policy never rewrites existing reservations',()=>{const s=seed();const snap=x=>JSON.stringify(x.reservations.map(r=>[r.id,r.status,r.depositStatus,r.depositAmount]));assert.equal(snap(eng.updatePolicy(s,{requireDeposit:false})),snap(s));assert.equal(snap(eng.updatePolicy(eng.updatePolicy(s,{requireDeposit:false}),{requireDeposit:true})),snap(s))});

test('no-show: a requested reservation cannot be a no-show, even after the grace period and even when the deposit is paid',()=>{let s=seed();s=eng.changeClock(s,isoAt(29,14));assert.equal(dRes(s,'RSV-1004').status,'requested');assert.throws(()=>eng.markNoShow(s,'RSV-1004'),/확정된 예약만/);const paid=eng.payDeposit(s,'RSV-1004');assert.throws(()=>eng.markNoShow(paid,'RSV-1004'),/확정된 예약만/);assert.equal(rules.canMarkNoShow(s,dRes(s,'RSV-1004')),false)});
test('no-show: an arrived reservation cannot become a no-show',()=>{let s=seed();s=eng.markArrived(s,'RSV-1006');s=eng.changeClock(s,isoAt(29,17));assert.throws(()=>eng.markNoShow(s,'RSV-1006'),/확정된 예약만/);assert.equal(rules.canMarkNoShow(s,dRes(s,'RSV-1006')),false)});
test('no-show: only a confirmed reservation after the grace period can be a no-show',()=>{let s=seed();assert.equal(rules.canMarkNoShow(s,dRes(s,'RSV-1002')),true);s=eng.markNoShow(s,'RSV-1002');assert.equal(dRes(s,'RSV-1002').status,'no_show');for(const id of ['RSV-1001','RSV-1005'])assert.equal(rules.canMarkNoShow(s,dRes(s,id)),false,id)});

function lcg(n){let x=n>>>0;return()=>((x=(Math.imul(x,1664525)+1013904223)>>>0)/2**32)}
function depositViolations(s){const bad=[];for(const r of s.reservations){const t=r.status,d=r.depositStatus;if(['cancelled','no_show'].includes(t)&&d==='paid')bad.push(`${t}+paid`);if(['refunded','forfeited'].includes(d)&&!['cancelled','no_show'].includes(t))bad.push(`${t}+${d}`);if(['confirmed','arrived','completed'].includes(t)&&d==='unpaid')bad.push(`${t}+unpaid`);if(d==='not_required'&&r.depositAmount!==0)bad.push('not_required with an amount')}return bad}
test('deposit invariants: random command sequences never produce a contradictory reservation/deposit state, and every state is a valid backup',()=>{
  const found=new Set();let steps=0;
  for(let sq=1;sq<=250;sq++){const rand=lcg(sq*7919);const pick=a=>a[Math.floor(rand()*a.length)];let s=seed();
    for(let i=0;i<40;i++){const r=s.reservations.length?pick(s.reservations):null,w=s.waitlist.length?pick(s.waitlist):null,op=Math.floor(rand()*13);const prior=r&&r.status;
      const ops=[()=>eng.createReservation(s,{customerId:pick(s.customers).id,serviceId:pick(s.services).id,staffId:pick(s.staff).id,startAt:isoAt(29+Math.floor(rand()*3),9+Math.floor(rand()*9),rand()<0.5?0:30)}),()=>eng.payDeposit(s,r.id),()=>eng.confirmReservation(s,r.id),()=>eng.markArrived(s,r.id),()=>eng.completeReservation(s,r.id),()=>eng.cancelReservation(s,r.id,'x'),()=>eng.markNoShow(s,r.id),()=>eng.offerCancelledSlot(s,w.id,pick(s.reservations.filter(x=>x.status==='cancelled')).id),()=>eng.acceptOffer(s,w.id),()=>eng.declineOffer(s,w.id),()=>eng.changeClock(s,new Date(new Date(s.simulatedNow).getTime()+Math.floor(rand()*8)*3600000).toISOString()),()=>eng.updatePolicy(s,{requireDeposit:rand()<0.5,noShowForfeit:rand()<0.5,lateCancelForfeit:rand()<0.5}),()=>eng.updatePolicy(s,{noShowForfeit:rand()<0.5})];
      let nx;try{nx=ops[op]()}catch{continue}
      s=nx;steps++;if(op===1&&!['requested','confirmed','arrived'].includes(prior))found.add(`paid a deposit on ${prior}`);if(op===5&&!['requested','confirmed'].includes(prior))found.add(`cancelled from ${prior}`);if(op===6&&prior!=='confirmed')found.add(`no-show from ${prior}`);
      for(const b of depositViolations(s))found.add(b);const v=bk.validateState(s);if(!v.ok)found.add('INVALID BACKUP: '+v.errors[0])}}
  assert.ok(steps>3000,`enough successful steps (${steps})`);assert.deepEqual([...found],[],'contradictory results: '+[...found].join(' | '))});
