const test=require('node:test');const assert=require('node:assert/strict');
const {makeSeed}=require('../.test-build/src/data/seed.js');
const rules=require('../.test-build/src/domain/rules.js');
const eng=require('../.test-build/src/domain/engine.js');
const {metrics}=require('../.test-build/src/domain/metrics.js');
const csv=require('../.test-build/src/lib/csv.js');
const {LocalRepository,STORAGE_KEY}=require('../.test-build/src/lib/repository.js');
const {parseBackup}=require('../.test-build/src/domain/validation.js');
const base=new Date(2026,8,29,8,0,0);const seed=()=>makeSeed(base);

test('seed has business data',()=>{const s=seed();assert.equal(s.services.length,3);assert.equal(s.staff.length,2);assert.equal(s.customers.length,8);assert.equal(s.reservations.length,8);assert.equal(s.waitlist.length,3)});
test('seed clock is deterministic around noon',()=>{const s=seed();assert.equal(new Date(s.simulatedNow).getHours(),12)});
test('cancelled reservation does not occupy slot',()=>{const s=seed();const r=s.reservations.find(x=>x.id==='RSV-1005');const c=rules.bookingCheck(s,{customerId:'CUS-006',serviceId:r.serviceId,staffId:r.staffId,startAt:r.startAt});assert.equal(c.ok,true)});
test('confirmed reservation blocks overlap',()=>{const s=seed();const r=s.reservations.find(x=>x.id==='RSV-1003');const c=rules.bookingCheck(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:r.staffId,startAt:r.startAt});assert.equal(c.ok,false);assert.match(c.reasons.join(' '),/겹칩니다/)});
test('staff capability is checked',()=>{const s=seed();s.staff.find(x=>x.id==='ST-B').serviceIds=['SVC-CUT'];const c=rules.bookingCheck(s,{customerId:'CUS-001',serviceId:'SVC-COLOR',staffId:'ST-B',startAt:new Date(2026,8,30,15).toISOString()});assert.equal(c.ok,false)});
test('business hours are checked',()=>{const s=seed();const c=rules.bookingCheck(s,{customerId:'CUS-001',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,29,20).toISOString()});assert.equal(c.ok,false)});
test('create reservation starts requested with unpaid deposit',()=>{let s=seed();s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});const r=s.reservations[0];assert.equal(r.status,'requested');assert.equal(r.depositStatus,'unpaid');assert.equal(r.depositAmount,10000)});
test('confirm before deposit is rejected',()=>{let s=seed();s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});assert.throws(()=>eng.confirmReservation(s,s.reservations[0].id),/예약금/)});
test('pay deposit then confirm works',()=>{let s=seed();s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});const id=s.reservations[0].id;s=eng.payDeposit(s,id);s=eng.confirmReservation(s,id);assert.equal(s.reservations.find(x=>x.id===id).status,'confirmed')});
test('deposit not required policy creates not_required',()=>{let s=seed();s.policy.requireDeposit=false;s=eng.createReservation(s,{customerId:'CUS-006',serviceId:'SVC-CUT',staffId:'ST-A',startAt:new Date(2026,8,30,16).toISOString()});assert.equal(s.reservations[0].depositStatus,'not_required')});
test('early cancellation refunds paid deposit',()=>{let s=seed();const id='RSV-1008';s=eng.cancelReservation(s,id,'일정 변경');const r=s.reservations.find(x=>x.id===id);assert.equal(r.status,'cancelled');assert.equal(r.depositStatus,'refunded')});
test('late cancellation forfeits paid deposit',()=>{let s=seed();s.policy.cancellationHours=48;s=eng.cancelReservation(s,'RSV-1006','당일 취소');assert.equal(s.reservations.find(x=>x.id==='RSV-1006').depositStatus,'forfeited')});
test('cancelled reservation cannot be cancelled twice',()=>{let s=seed();assert.throws(()=>eng.cancelReservation(s,'RSV-1005','again'),/종료된 예약/)});
test('arrival only from confirmed',()=>{let s=seed();s=eng.markArrived(s,'RSV-1006');assert.equal(s.reservations.find(x=>x.id==='RSV-1006').status,'arrived');assert.throws(()=>eng.markArrived(s,'RSV-1004'))});
test('complete increments customer visits',()=>{let s=seed();const before=s.customers.find(x=>x.id==='CUS-007').visitCount;s=eng.completeReservation(s,'RSV-1006');assert.equal(s.customers.find(x=>x.id==='CUS-007').visitCount,before+1)});
test('no-show is allowed after grace',()=>{let s=seed();s=eng.markNoShow(s,'RSV-1002');const r=s.reservations.find(x=>x.id==='RSV-1002');assert.equal(r.status,'no_show');assert.equal(r.depositStatus,'forfeited');assert.equal(s.customers.find(x=>x.id==='CUS-002').noShowCount,2)});
test('no-show before grace is rejected',()=>{let s=seed();s=eng.changeClock(s,new Date(2026,8,29,10,35).toISOString());assert.throws(()=>eng.markNoShow(s,'RSV-1002'),/10분/)});
test('cancelled slot has two matching waiters',()=>{const s=seed(),r=s.reservations.find(x=>x.id==='RSV-1005');const m=rules.waitlistMatches(s,{reservationId:r.id,serviceId:r.serviceId,staffId:r.staffId,startAt:r.startAt,endAt:r.endAt});assert.equal(m.length,2)});
test('waitlist offer changes status and sets expiry',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const w=s.waitlist.find(x=>x.id==='WAIT-001');assert.equal(w.status,'offered');assert.equal(w.offer.status,'open');assert.ok(new Date(w.offer.expiresAt)>new Date(w.offer.sentAt))});
test('nonmatching waiter cannot receive slot',()=>{const s=seed();assert.throws(()=>eng.offerCancelledSlot(s,'WAIT-003','RSV-1005'),/맞지 않습니다/)});
test('accept offer creates recovered confirmed reservation',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const before=s.reservations.length;s=eng.acceptOffer(s,'WAIT-001');assert.equal(s.reservations.length,before+1);assert.equal(s.reservations[0].source,'waitlist');assert.equal(s.reservations[0].status,'confirmed');assert.equal(s.waitlist.find(x=>x.id==='WAIT-001').status,'booked')});
test('decline offer returns waiter to waiting',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');s=eng.declineOffer(s,'WAIT-001');assert.equal(s.waitlist.find(x=>x.id==='WAIT-001').status,'waiting')});
test('offer expires when clock passes hold',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const expiry=s.waitlist.find(x=>x.id==='WAIT-001').offer.expiresAt;s=eng.changeClock(s,new Date(new Date(expiry).getTime()+60000).toISOString());const w=s.waitlist.find(x=>x.id==='WAIT-001');assert.equal(w.status,'waiting');assert.equal(w.offer.status,'expired')});
test('accepting stale offer after competing booking is blocked',()=>{let s=seed();s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');const slot=s.reservations.find(x=>x.id==='RSV-1005').startAt;s=eng.createReservation(s,{customerId:'CUS-008',serviceId:'SVC-CUT',staffId:'ST-A',startAt:slot});const rid=s.reservations[0].id;s=eng.payDeposit(s,rid);s=eng.confirmReservation(s,rid);assert.throws(()=>eng.acceptOffer(s,'WAIT-001'),/겹칩니다/)});
test('add waitlist rejects reversed window',()=>{const s=seed();assert.throws(()=>eng.addWaitlist(s,{customerId:'CUS-001',serviceId:'SVC-CUT',staffId:null,windowStart:new Date(2026,8,30,15).toISOString(),windowEnd:new Date(2026,8,30,14).toISOString(),note:''}),/희망 시간/)});
test('add customer creates record',()=>{const s=eng.addCustomer(seed(),{name:'테스트 고객',phone:'010',email:'a@test'});assert.equal(s.customers[0].name,'테스트 고객')});
test('invalid policy hours rejected',()=>{const s=seed();assert.throws(()=>eng.updatePolicy(s,{openingHour:20,closingHour:19}),/영업 시작/)});
test('candidate slots return only free times',()=>{const s=seed();const d=rules.dayKey(s.simulatedNow);const slots=rules.candidateSlots(s,d,'ST-A','SVC-CUT');assert.ok(slots.length>0);assert.equal(slots.some(x=>x===s.reservations.find(r=>r.id==='RSV-1003').startAt),false)});
test('metrics count waiting and recovered',()=>{let s=seed();let m=metrics(s);assert.equal(m.waiting,3);assert.equal(m.recovered,0);s=eng.offerCancelledSlot(s,'WAIT-001','RSV-1005');s=eng.acceptOffer(s,'WAIT-001');m=metrics(s);assert.ok(m.recovered>0)});
test('csv parser supports quoted commas',()=>{const rows=csv.parseCsv('id,name\n1,"Kim, Mina"\n');assert.equal(rows[1][1],'Kim, Mina')});
test('customer CSV detects duplicate id',()=>{const s=seed();const p=csv.previewCustomersCsv('id,name,phone,email\nCUS-001,dup,1,a@x\n',s);assert.equal(p.issues.length,1)});
test('valid customer CSV previews one row',()=>{const s=seed();const p=csv.previewCustomersCsv('id,name,phone,email\nCUS-900,새고객,010,a@x\n',s);assert.equal(p.issues.length,0);assert.equal(p.rows.length,1)});
test('reservation CSV detects overlap',()=>{const s=seed();const r=s.reservations.find(x=>x.id==='RSV-1003');const text=`id,customerId,serviceId,staffId,startAt,note\nRSV-X,CUS-006,SVC-CUT,ST-A,${r.startAt},x\n`;const p=csv.previewReservationsCsv(text,s);assert.equal(p.issues.length,1)});
test('reservation CSV accepts free slot',()=>{const s=seed();const text=`id,customerId,serviceId,staffId,startAt,note\nRSV-X,CUS-006,SVC-CUT,ST-B,${new Date(2026,8,30,17).toISOString()},x\n`;const p=csv.previewReservationsCsv(text,s);assert.equal(p.issues.length,0);assert.equal(p.rows[0].status,'requested')});
test('imported customers are appended',()=>{const s=seed();const p=csv.previewCustomersCsv('id,name,phone,email\nCUS-900,새고객,010,a@x\n',s);const n=csv.applyImportedCustomers(s,p.rows);assert.equal(n.customers.length,s.customers.length+1)});
test('backup parser roundtrips valid state',()=>{const s=seed();const p=parseBackup(JSON.stringify(s));assert.equal(p.reservations.length,s.reservations.length)});
test('backup parser rejects wrong schema',()=>{const s=seed();s.schemaVersion=2;assert.throws(()=>parseBackup(JSON.stringify(s)),/지원하지 않는/)});
test('repository session mode works without storage',()=>{const repo=new LocalRepository(null);const r=repo.load();assert.equal(r.mode,'session');repo.save(r.state)});
test('repository detects concurrent changes',()=>{const mem=new Map();const storage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};const repo=new LocalRepository(storage);const loaded=repo.load();mem.set(STORAGE_KEY,'other');assert.throws(()=>repo.save(loaded.state),/다른 탭/)});
test('repository replace keeps old data on quota failure',()=>{let old='';const storage={getItem:()=>old,setItem:(k,v)=>{if(v.length>20000)throw Error('quota');old=v},removeItem:()=>{}};const repo=new LocalRepository(storage);const initial=repo.load();repo.save(initial.state);const before=old;const big=structuredClone(initial.state);for(let i=0;i<200;i++)big.audit.push({id:'X'+i,at:big.simulatedNow,type:'system',entityId:'x',message:'x'.repeat(50)});assert.throws(()=>repo.replace(big),/저장 공간/);assert.equal(old,before)});
test('audit is written for state changes',()=>{let s=seed();const before=s.audit.length;s=eng.payDeposit(s,'RSV-1004');assert.equal(s.audit.length,before+1)});

// ---- P0-1 regression: policy values are validated in the engine, the Policies screen, restore and localStorage loading.
// Before the fix slotMinutes <= 0 was saved as-is and rules.candidateSlots looped forever (froze the schedule screen).
const polMod=require('../.test-build/src/domain/policy.js');const vld=require('../.test-build/src/domain/validation.js');
const {spawnSync}=require('node:child_process');const nodePath=require('node:path');
const BUILD=nodePath.resolve(__dirname,'../.test-build/src').replace(/\\/g,'/');
// Risky cases run in a child process with a timeout so a regression fails the test instead of hanging the whole test run.
const isolated=code=>{const r=spawnSync(process.execPath,['-e',`const B='${BUILD}/';const {makeSeed}=require(B+'data/seed.js');const rules=require(B+'domain/rules.js');const vld=require(B+'domain/validation.js');const seed=()=>makeSeed(new Date(2026,8,29,8,0,0));${code}`],{timeout:8000,encoding:'utf8'});return {hung:!!r.error,status:r.status,out:(r.stdout||'').trim(),err:(r.stderr||'').trim()};};
const memStore=raw=>{let v=raw;return{getItem:()=>v,setItem:(k,x)=>{v=x},removeItem:()=>{v=null}}};
const rejectPolicy=(patch,re)=>assert.throws(()=>eng.updatePolicy(seed(),patch),re);
const DEFAULT_SLOT_COUNT=7; // free 30-minute start times of ST-A / SVC-CUT on the seed day

test('policy: slotMinutes = 0 is rejected and the state is untouched',()=>{const s=seed();const before=JSON.stringify(s);rejectPolicy({slotMinutes:0},/기본 슬롯/);assert.throws(()=>eng.updatePolicy(s,{slotMinutes:0}),/기본 슬롯/);assert.equal(JSON.stringify(s),before)});
test('policy: negative slotMinutes is rejected',()=>{rejectPolicy({slotMinutes:-1},/기본 슬롯/);rejectPolicy({slotMinutes:-30},/기본 슬롯/)});
test('policy: NaN / Infinity / non-number slotMinutes is rejected',()=>{for(const v of [NaN,Infinity,-Infinity,null,undefined,'30','abc'])rejectPolicy({slotMinutes:v},/기본 슬롯/)});
test('policy: too small, too large or fractional slotMinutes is rejected',()=>{for(const v of [1,4,241,1e9,1e-9,7.5])rejectPolicy({slotMinutes:v},/기본 슬롯/)});
test('policy: invalid opening/closing hours are rejected',()=>{rejectPolicy({openingHour:-1},/영업 시작 시/);rejectPolicy({openingHour:24},/영업 시작 시/);rejectPolicy({closingHour:0},/영업 종료 시/);rejectPolicy({closingHour:25},/영업 종료 시/);rejectPolicy({openingHour:9.5},/영업 시작 시/);rejectPolicy({closingHour:NaN},/영업 종료 시/);rejectPolicy({openingHour:Infinity},/영업 시작 시/);rejectPolicy({openingHour:19,closingHour:9},/영업 시작 시간은 종료 시간보다 빨라야/);rejectPolicy({openingHour:10,closingHour:10},/영업 시작 시간은 종료 시간보다 빨라야/)});
test('policy: negative or non-finite cancellationHours is rejected, zero is allowed',()=>{for(const v of [-1,-0.5,NaN,Infinity,'24',8761])rejectPolicy({cancellationHours:v},/취소 기준 시간/);assert.equal(eng.updatePolicy(seed(),{cancellationHours:0}).policy.cancellationHours,0)});
test('policy: negative or non-finite noShowGraceMin is rejected, zero is allowed',()=>{for(const v of [-1,-30,NaN,Infinity,'10',1441])rejectPolicy({noShowGraceMin:v},/노쇼 유예/);assert.equal(eng.updatePolicy(seed(),{noShowGraceMin:0}).policy.noShowGraceMin,0)});
test('policy: offerHoldMin must be a positive finite number (0 is rejected)',()=>{for(const v of [0,-1,-20,NaN,Infinity,'20',10081])rejectPolicy({offerHoldMin:v},/제안 홀드/);assert.equal(eng.updatePolicy(seed(),{offerHoldMin:0.5}).policy.offerHoldMin,0.5)});
test('policy: several problems are all reported in one message',()=>{try{eng.updatePolicy(seed(),{slotMinutes:0,offerHoldMin:0,cancellationHours:-1});assert.fail('should throw')}catch(e){assert.match(e.message,/기본 슬롯/);assert.match(e.message,/제안 홀드/);assert.match(e.message,/취소 기준 시간/)}});
test('policy: valid values are saved as before and slot calculation follows them',()=>{const s=seed();const before=rules.candidateSlots(s,rules.dayKey(s.simulatedNow),'ST-A','SVC-CUT');assert.equal(before.length,DEFAULT_SLOT_COUNT);const n=eng.updatePolicy(s,{slotMinutes:15,openingHour:10,closingHour:18,cancellationHours:12,noShowGraceMin:5,offerHoldMin:30});assert.deepEqual([n.policy.slotMinutes,n.policy.openingHour,n.policy.closingHour,n.policy.cancellationHours,n.policy.noShowGraceMin,n.policy.offerHoldMin],[15,10,18,12,5,30]);assert.equal(n.revision,s.revision+1);assert.equal(n.audit.length,s.audit.length+1);const slots=rules.candidateSlots(n,rules.dayKey(n.simulatedNow),'ST-A','SVC-CUT');assert.ok(slots.length>0);for(const x of slots){const d=new Date(x);assert.equal(d.getMinutes()%15,0);assert.ok(d.getHours()>=10);const e=new Date(rules.addMinutes(x,70));assert.ok(e.getHours()*60+e.getMinutes()<=18*60)}assert.ok(slots.length>before.length)});
test('policy: boundary values are accepted, one step outside is rejected',()=>{const ok={slotMinutes:5,openingHour:0,closingHour:24,cancellationHours:0,noShowGraceMin:0,offerHoldMin:10080};assert.deepEqual(polMod.policyProblems({...seed().policy,...ok}),[]);assert.equal(eng.updatePolicy(seed(),{slotMinutes:240,cancellationHours:8760,noShowGraceMin:1440,openingHour:23,closingHour:24}).policy.slotMinutes,240)});
test('policy: unchanged default seed policy is valid and matches the documented defaults',()=>{const p=seed().policy;assert.deepEqual(polMod.policyProblems(p),[]);for(const f of Object.keys(polMod.POLICY_DEFAULTS))assert.equal(p[f],polMod.POLICY_DEFAULTS[f],f)});
test('policy: updating unrelated fields still works with a valid policy',()=>{const n=eng.updatePolicy(seed(),{businessName:'새 이름',requireDeposit:false});assert.equal(n.policy.businessName,'새 이름');assert.equal(n.policy.requireDeposit,false);assert.equal(n.policy.slotMinutes,30)});
test('policyProblems reports each bad field and the hours order',()=>{const fields=polMod.policyProblems({slotMinutes:0,openingHour:20,closingHour:19,cancellationHours:-1,noShowGraceMin:-1,offerHoldMin:0}).map(x=>x.field).sort();assert.deepEqual(fields,['cancellationHours','hours','noShowGraceMin','offerHoldMin','slotMinutes']);assert.equal(polMod.policyProblems(null).length,6);assert.deepEqual(polMod.policyProblems(undefined).map(x=>x.field).sort(),['cancellationHours','closingHour','noShowGraceMin','offerHoldMin','openingHour','slotMinutes'])});
test('repairPolicy replaces only the invalid values and keeps everything else',()=>{const p={...seed().policy,slotMinutes:0,cancellationHours:12,noShowGraceMin:-1,businessName:'유지'};const r=polMod.repairPolicy(p);assert.equal(r.policy.slotMinutes,30);assert.equal(r.policy.cancellationHours,12);assert.equal(r.policy.noShowGraceMin,10);assert.equal(r.policy.businessName,'유지');assert.equal(r.fixes.length,2);assert.equal(polMod.repairPolicy(seed().policy).fixes.length,0)});
test('repairPolicy resets the whole opening range when the order is wrong',()=>{const r=polMod.repairPolicy({...seed().policy,openingHour:20,closingHour:19});assert.deepEqual([r.policy.openingHour,r.policy.closingHour],[9,19]);assert.equal(r.fixes.length,1)});

test('restore/load: backups with bad policy values load without hanging and are repaired with a notice and an audit entry',()=>{
  const r=isolated(`const cases=[{slotMinutes:0},{slotMinutes:-30},{slotMinutes:null},{slotMinutes:'abc'},{slotMinutes:1e-9},{slotMinutes:1e9},{openingHour:20,closingHour:19},{closingHour:1e9},{closingHour:null},{cancellationHours:-1},{noShowGraceMin:-5},{offerHoldMin:0},{slotMinutes:0,offerHoldMin:0,closingHour:-3}];const out=cases.map(c=>{const s=seed();s.policy={...s.policy,...c};const p=vld.parseBackupWithNotes(JSON.stringify(s));const slots=rules.candidateSlots(p.state,rules.dayKey(p.state.simulatedNow),'ST-A','SVC-CUT');return{notes:p.notes.length,slots:slots.length,slot:p.state.policy.slotMinutes,name:p.state.policy.businessName,audit:p.state.audit[0].type+':'+p.state.audit[0].message.includes('기본값'),res:p.state.reservations.length}});console.log(JSON.stringify(out));`);
  assert.equal(r.hung,false,'loading a backup with a bad policy must not hang');assert.equal(r.status,0,r.err);const out=JSON.parse(r.out);assert.equal(out.length,13);for(const o of out){assert.equal(o.notes,1);assert.equal(o.slots,DEFAULT_SLOT_COUNT);assert.equal(o.name,seed().policy.businessName);assert.equal(o.audit,'policy:true');assert.equal(o.res,8)}});
test('restore: a repaired backup keeps all other data and the resulting policy is valid',()=>{const s=seed();s.policy={...s.policy,slotMinutes:0,cancellationHours:-2};const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.deepEqual(polMod.policyProblems(p.state.policy),[]);assert.equal(p.state.policy.cancellationHours,24);assert.equal(p.state.reservations.length,s.reservations.length);assert.equal(p.state.customers.length,s.customers.length);assert.equal(p.state.waitlist.length,s.waitlist.length);assert.equal(p.state.audit.length,s.audit.length+1);assert.match(p.notes[0],/기본 슬롯\(분\) 0 → 30/);assert.match(p.notes[0],/취소 기준 시간 -2 → 24/)});
test('restore: a valid backup produces no notes and no extra audit entry',()=>{const s=seed();const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.deepEqual(p.notes,[]);assert.equal(p.state.audit.length,s.audit.length);assert.deepEqual(vld.parseBackup(JSON.stringify(s)).policy,s.policy)});
test('restore: a policy object without the numeric fields is repaired, unknown fields are kept',()=>{const s=seed();s.policy={hello:1};const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.equal(p.state.policy.hello,1);for(const f of Object.keys(polMod.POLICY_DEFAULTS))assert.equal(p.state.policy[f],polMod.POLICY_DEFAULTS[f])});
test('restore: the audit log stays within the load-time limit after a repair',()=>{const s=seed();s.policy.slotMinutes=0;s.audit=Array.from({length:10000},(_,i)=>({id:'A'+i,at:s.simulatedNow,type:'system',entityId:'x',message:'m'}));const p=vld.parseBackupWithNotes(JSON.stringify(s));assert.equal(p.state.audit.length,10000);assert.doesNotThrow(()=>vld.parseState(p.state))});
test('localStorage load: a stored state with a bad policy loads in normal mode with a notice, keeps the raw original and does not hang',()=>{
  const s=seed();s.policy={...s.policy,slotMinutes:0,offerHoldMin:-4};const raw=JSON.stringify(s);const st=memStore(raw);const repo=new LocalRepository(st);const t0=Date.now();const loaded=repo.load();assert.ok(Date.now()-t0<2000);assert.equal(loaded.mode,'persistent');assert.match(loaded.notice,/정책 값이 올바르지 않아 기본값으로 바꿨습니다/);assert.match(loaded.notice,/기본 슬롯\(분\) 0 → 30/);assert.match(loaded.notice,/저장된 원본은 그대로/);assert.deepEqual(polMod.policyProblems(loaded.state.policy),[]);assert.equal(loaded.state.reservations.length,s.reservations.length);assert.equal(repo.raw(),raw,'the stored original is not overwritten by loading');
  const slots=rules.candidateSlots(loaded.state,rules.dayKey(loaded.state.simulatedNow),'ST-A','SVC-CUT');assert.equal(slots.length,DEFAULT_SLOT_COUNT);
  repo.save(eng.payDeposit(loaded.state,'RSV-1004'));assert.deepEqual(polMod.policyProblems(JSON.parse(st.getItem(STORAGE_KEY)).policy),[]);const again=new LocalRepository(st).load();assert.equal(again.notice,'');assert.equal(again.mode,'persistent')});
test('localStorage load: a valid stored state loads with no notice',()=>{const st=memStore(JSON.stringify(seed()));const l=new LocalRepository(st).load();assert.equal(l.mode,'persistent');assert.equal(l.notice,'')});
test('repository.replace persists a repaired policy, never the bad one',()=>{const st=memStore(null);const repo=new LocalRepository(st);repo.load();const bad=seed();bad.policy={...bad.policy,slotMinutes:-30,closingHour:1e9};repo.replace(bad);assert.deepEqual(polMod.policyProblems(JSON.parse(st.getItem(STORAGE_KEY)).policy),[])});
test('candidateSlots never loops forever, even if a bad policy reaches memory directly',()=>{
  const r=isolated(`const one=(patch)=>{const s=seed();Object.assign(s.policy,patch);return rules.candidateSlots(s,rules.dayKey(s.simulatedNow),'ST-A','SVC-CUT').length;};const out=[{slotMinutes:0},{slotMinutes:-30},{slotMinutes:NaN},{slotMinutes:1e-9},{slotMinutes:Infinity},{slotMinutes:'x'},{closingHour:1e9},{openingHour:NaN},{openingHour:20,closingHour:19}].map(one);console.log(JSON.stringify(out));`);
  // Reversed hours only reach memory by bypassing every validation path; bookingCheck then rejects every candidate, so the result is an empty list - but never a hang.
  assert.equal(r.hung,false,'candidateSlots must not hang');assert.equal(r.status,0,r.err);assert.deepEqual(JSON.parse(r.out),[...new Array(8).fill(DEFAULT_SLOT_COUNT),0])});

