import React,{useRef,useState} from 'react';import {useData} from '../store';import {PageHeading,Help,Button,Field,Confirm,Modal} from '../components/ui';import {changeClock} from '../domain/engine';import {localInput} from '../domain/rules';import {downloadText} from '../lib/files';import {backupLimit} from '../domain/validation';import {BackupInspection,RESTORE_CONFIRM_TEXT,backupTooLarge,canConfirmRestore,describeRestore,inspectBackup} from '../domain/backup';
type Pending={name:string;size:number;result:BackupInspection};
const fmtDelta=(a:number,b:number)=>b===a?'변화 없음':`${b>a?'+':''}${b-a}`;
const fmtTime=(iso:string)=>new Date(iso).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const failure=(name:string,size:number,message:string):Pending=>({name,size,result:{ok:false,errors:[message],totalErrors:1,notes:[]}});
export function Settings(){const{state,run,replace,reset,raw}=useData();const[clock,setClock]=useState(localInput(state.simulatedNow));const[confirm,setConfirm]=useState(false);const input=useRef<HTMLInputElement>(null);const rawText=raw()??JSON.stringify(state);const usage=Math.min(100,Math.round(rawText.length/5_200_000*100));
  const[pending,setPending]=useState<Pending|null>(null);const[typed,setTyped]=useState('');const[failed,setFailed]=useState('');const[last,setLast]=useState('');
  function backup(){downloadText(`reservation-lab-backup-${Date.now()}.json`,JSON.stringify(state,null,2),'application/json;charset=utf-8')}
  // Step 1: picking a file never changes anything. It is only read and inspected; the result decides which dialog is shown.
  async function pick(file:File){setFailed('');setTyped('');try{if(backupTooLarge(file.size)){setPending(failure(file.name,file.size,`백업 파일이 너무 큽니다 (${(file.size/1e6).toFixed(1)}MB). 약 4MB 이하로 줄여 주세요.`));return}const text=await file.text();setPending({name:file.name,size:file.size,result:inspectBackup(text)})}catch(e){setPending(failure(file.name,file.size,`파일을 읽지 못했습니다: ${(e as Error).message}`))}finally{if(input.current)input.current.value=''}}
  function closeRestore(){setPending(null);setTyped('');setFailed('')}
  // Step 2: only a valid inspection plus the exact confirmation word can restore. If saving fails, the current data stays as it is.
  function apply(){if(!pending||!pending.result.state||!canConfirmRestore(pending.result,typed))return;const next=pending.result.state;const notes=pending.result.notes;const message=notes.length?'백업을 복원했습니다. 올바르지 않은 정책 값은 기본값으로 바꿨습니다(감사 이력에 기록).':'백업을 복원했습니다.';if(replace(next,message)){setLast(`${pending.name} · 예약 ${next.reservations.length}건 · 고객 ${next.customers.length}명 · 대기자 ${next.waitlist.length}건${notes.length?' · 정책 값 자동 복구':''}`);closeRestore()}else setFailed('복원을 저장하지 못했습니다. 현재 자료는 그대로입니다. 브라우저 저장 공간을 확인한 뒤 다시 시도하세요.')}
  const summary=pending&&pending.result.ok&&pending.result.state?describeRestore(state,pending.result.state):null;
  return <><PageHeading eyebrow="LOCAL STORAGE & BACKUP" title="설정 · 백업" description="실습 시각을 움직여 시간 의존 규칙을 시험하고, 로컬 자료를 JSON으로 백업·복원합니다."/><Help title="백엔드 없는 앱의 경계">브라우저 저장은 한 사람의 한 브라우저에서 배우기에는 편하지만 팀 동시 작업, 서버 백업, 진짜 로그인 권한은 제공하지 않습니다. 그래서 데이터를 파일로 꺼낼 수 있게 해 둡니다.</Help><div className="two-column"><section className="panel"><h2>실습 시각</h2><Field label="현재 가상 시각" hint="노쇼·취소 기준은 실제 컴퓨터 시계가 아니라 이 값을 사용합니다."><input type="datetime-local" value={clock} onChange={e=>setClock(e.target.value)}/></Field><div className="action-row"><Button variant="primary" onClick={()=>run(s=>changeClock(s,new Date(clock).toISOString()),'실습 시각을 변경했습니다.')}>시각 적용</Button><Button onClick={()=>{const d=new Date(state.simulatedNow);d.setMinutes(d.getMinutes()+30);setClock(localInput(d.toISOString()));run(s=>changeClock(s,d.toISOString()),'30분 이동했습니다.')}}>+30분</Button><Button onClick={()=>{const d=new Date(state.simulatedNow);d.setDate(d.getDate()+1);setClock(localInput(d.toISOString()));run(s=>changeClock(s,d.toISOString()),'하루 이동했습니다.')}}>+1일</Button></div></section><section className="panel"><h2>브라우저 저장</h2><div className="detail-row"><span>현재 JSON 크기</span><b>{Math.round(rawText.length/1024)} KB</b></div><div className="detail-row"><span>브라우저 5.2M자 가정 사용률</span><b>{usage}%</b></div><div className="storage-meter"><i style={{width:`${usage}%`}}/></div><p className="panel-sub">백업 입력 자체는 약 {Math.round(backupLimit()/100000)/10}MB 문자 한도로 제한합니다. 브라우저별 localStorage 실제 한도는 다를 수 있습니다.</p></section></div><div className="two-column" style={{marginTop:18}}><section className="panel"><h2>백업 · 복원</h2><div className="action-row"><Button icon="download" onClick={backup}>전체 JSON 백업</Button><Button onClick={()=>input.current?.click()}>백업 복원</Button><input ref={input} hidden type="file" accept=".json,application/json" aria-label="백업 JSON 파일 선택" onChange={e=>e.target.files?.[0]&&pick(e.target.files[0])}/></div><div className="notice-box" style={{marginTop:14}}>백업 파일을 고르면 먼저 검사하고 ‘복원 미리보기’를 보여 줍니다. 미리보기에서 ‘{RESTORE_CONFIRM_TEXT}’을 직접 입력해야만 현재 자료가 교체됩니다. 검사에 실패하거나 저장 공간이 부족하면 현재 자료는 그대로 유지됩니다.</div>{last&&<div className="notice-box" role="status" style={{marginTop:10}}><b>마지막 복원</b> · {last}</div>}</section><section className="panel"><h2>실습 초기화</h2><p>현재 입력한 자료를 지우고 처음의 가상 예약점 데이터로 돌아갑니다.</p><Button variant="danger" onClick={()=>setConfirm(true)}>가상 자료로 초기화</Button></section></div>
  {confirm&&<Confirm title="실습 자료를 초기화할까요?" description="현재 브라우저의 실습 데이터가 기본 가상 데이터로 바뀝니다. 필요한 내용은 먼저 JSON 백업하세요." button="초기화" danger onClose={()=>setConfirm(false)} onConfirm={()=>{reset();setConfirm(false)}}/>}
  {pending&&!pending.result.ok&&<Modal title="백업 파일을 복원할 수 없습니다" onClose={closeRestore}><p className="confirm-copy"><b>{pending.name}</b> 검사에서 오류 {pending.result.totalErrors}개를 찾았습니다. <b>현재 자료는 전혀 변경되지 않았습니다.</b> 이 앱에서 내려받은 백업 파일인지, 파일이 수정되거나 손상되지 않았는지 확인하세요.</p><ul className="issue-list" aria-label="백업 검사 오류">{pending.result.errors.slice(0,20).map((x,i)=><li key={i}>{x}</li>)}</ul>{pending.result.totalErrors>20&&<p className="panel-sub">…외 {pending.result.totalErrors-20}개의 오류가 더 있습니다.</p>}<div className="modal-actions"><Button variant="primary" onClick={closeRestore}>닫기</Button></div></Modal>}
  {pending&&pending.result.ok&&summary&&<Modal title="백업 복원 미리보기" wide onClose={closeRestore}><p className="confirm-copy"><b>{pending.name}</b> ({Math.max(1,Math.round(pending.size/1024))} KB)은 검사를 통과했습니다. <b>아직 아무것도 바뀌지 않았습니다.</b> 아래 변경 내용을 확인한 뒤 복원하세요.</p>
    <div className="detail-stack">{summary.rows.map(r=><div className="detail-row" key={r.label}><span>{r.label}</span><b>{r.current} → {r.next} <small>({fmtDelta(r.current,r.next)})</small></b></div>)}</div>
    <h3 style={{marginTop:16}}>예약·대기자 상태별</h3><div className="detail-stack">{[...summary.reservationStatus,...summary.waitlistStatus].filter(r=>r.current||r.next).map(r=><div className="detail-row" key={r.label}><span>{r.label}</span><b>{r.current} → {r.next}</b></div>)}</div>
    <div className="detail-stack" style={{marginTop:12}}><div className="detail-row"><span>현재에만 있어 사라지는 자료</span><b>{summary.onlyInCurrent.map(r=>`${r.label} ${r.current}`).join(' · ')}</b></div><div className="detail-row"><span>백업에만 있어 새로 생기는 자료</span><b>{summary.onlyInBackup.map(r=>`${r.label} ${r.next}`).join(' · ')}</b></div><div className="detail-row"><span>실습 시각</span><b>{fmtTime(summary.clock.current)} → {fmtTime(summary.clock.next)}</b></div><div className="detail-row"><span>정책 변경</span><b>{summary.policyChanges.length?summary.policyChanges.join(' · '):'변경 없음'}</b></div></div>
    {pending.result.notes.length>0&&<div className="notice-box" role="status" style={{marginTop:12,background:'#fff8e6',borderColor:'#f0d9a0'}}><b>정책 값 자동 복구</b><br/>백업의 정책 값 일부가 올바르지 않아 복원할 때 기본값으로 바꿉니다. 나머지 자료는 그대로 복원되며, 복구 내용은 감사 이력에 기록됩니다.<br/><small>{pending.result.notes.join(' ')}</small></div>}
    <div className="notice-box" style={{marginTop:12,background:'#fff3f2',borderColor:'#f1c9c5',color:'#9b3933'}}>현재 자료 전체가 위 백업으로 교체됩니다. 기존 자료와 병합하지 않습니다. 현재 자료가 필요하면 먼저 ‘전체 JSON 백업’을 받으세요.</div>
    <Field label={`계속하려면 ‘${RESTORE_CONFIRM_TEXT}’을 입력하세요`}><input value={typed} onChange={e=>setTyped(e.target.value)} autoComplete="off" aria-label="복원 확인 문구"/></Field>{failed&&<ul className="issue-list" role="alert"><li>{failed}</li></ul>}
    <div className="modal-actions"><Button onClick={closeRestore}>취소</Button><Button variant="primary" disabled={!canConfirmRestore(pending.result,typed)} onClick={apply}>전체 자료 복원</Button></div></Modal>}
  </>}
